### ISSUE TITLE
RUN-ERROR with Python and Java

### ISSUE THREAD

**Issue by ACMatFSU** [DOMjudge/domjudge#126]
any python or java solutions return a **run-error**

the errors looks like:

``` C
Non-zero exitcode 127
*** Program stderr output following ***
/testcase001/execdir/program: 11: exec: python: not found
```

but both java and python are installed... I must have missed something.

**Comment by ztrk1600** [comment]
I found some comments in the compile wrapper-script of some interpreter-based language.
[](https://github.com/jcxavier/judgehost/blob/master/domjudge-3.1.3/judge/compile_perl.sh)

> \# NOTICE: this compiler script cannot be used with the USE_CHROOT
> \# configuration option turned on! (Unless proper preconfiguration of
> \# the chroot environment has been taken care of.)

Because the interpreter doesn't exist in the chroot'ed dictionary, it can't be found.
But I still don't know how to do the preconfiguration.

**Comment by eldering** [comment]
Please don't post to (old) issues, unless you're specifically addressing them.
Also, questions such as yours are better suited for the [emaillist](https://www.domjudge.org/mailman/listinfo/domjudge-devel) than these issue pages which are meant for reporting bugs and feature requests. Please send your question there and we'll be happy to answer it.
