### ISSUE TITLE
Jury submissions should be judged with low priority

### ISSUE THREAD

**Issue by 0xJoey** [DOMjudge/domjudge#1303]
Currently, Jury submissions have equal priority to contestant submissions.

**Comment by 0xJoey** [comment]
@RagnarGrootKoerkamp

**Comment by RagnarGrootKoerkamp** [comment]
Contest: We were re-adding problems for the main contest during the testsession, and the corresponding jury submissions took priority over team submissions from the testsession

**Comment by meisterT** [comment]
The normal prioritization should take of this naturally since you add all of these submissions as one team. See the comment and implementation here:
https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Service/DOMJudgeService.php#L1228

Doesn't that match what you have been seeing?

**Comment by RagnarGrootKoerkamp** [comment]
@mpsijm Do you remember the precise behavior we saw? I wasn't paying close attention at the time.

**Comment by mpsijm** [comment]
We were doing two things during the test session:
1. Changing the time limit of a problem and rejudging all submissions for that problem. When doing so, you can select "priority" as "low", "medium", or "high" (which we set to "low", to not interfere with the test session). This works as expected, as the rejudgings were only run after all submissions for the test session were done being judged (15 minutes after the test session ended).
2. Completely deleting a problem and re-uploading it, because all test cases were changed. When doing so, we could not select a priority, and it seemed like the jury submissions of this problem had priority over the team submissions for the test session, because all the jury submissions were judged before it continued with the team submissions for the test session again. I don't think this matches the behaviour in the comments of the function that @meisterT mentioned.

Of course, we would have had less problems with this if there would have been more than one judge host alive during the test session, but ah well, that's what happened. :joy:

**Comment by meisterT** [comment]
Thanks @mpsijm - that shouldn't have happened. I'll have a closer look to see what was going on and how to fix it.

**Comment by RagnarGrootKoerkamp** [comment]
Ah, one additional thing I just remembered:

We were running the *testsession*, but we re-uploaded a problem in the
*main contest*. So maybe the current prioritization only works inside a
single contest, not across multiple contests.

**Comment by meisterT** [comment]
I am working on a visualization that I want to add to DOMjudge eventually, but requires some tweaks before I can do so.

For this particular case, this is how it currently looks:
![image](https://user-images.githubusercontent.com/418721/140320954-5b39fb17-339f-4e25-b9c2-ee3d13a28086.png)

It shows what each judgehost was busy with. You clearly see some setup, the test session and the actual contest (where you added more machines in the middle?).

Zooming in, you can see that each judgehost is basically two rows, one for the judging it was working on and one for all the judgetasks, but the second row I labeled with the team ID to understand this issue better.

![image](https://user-images.githubusercontent.com/418721/140321435-aff2fac3-4b4f-4bd2-a3b6-5b1fabb27bb8.png)

Zooming out again on the relevant time during the test session, I double clicked one judgetask by team 1 to highlight all of them:

![image](https://user-images.githubusercontent.com/418721/140322036-671caf95-f109-4e61-bf41-6063c22db946.png)

From that it doesn't look like the submissions from team 1 took priority over normal team submissions. There's still the chance that I visualized stuff wrong since I had to filter out negative duration where I don't know how they came to be.

**Comment by meisterT** [comment]
Did you disable judging for some time during the test session (e.g. disable the judgehost or by an internal error)?

![image](https://user-images.githubusercontent.com/418721/140323542-4b42e4c5-dea0-471d-9074-6c0c2abcbf79.png)

**Comment by mvr320** [comment]
> 
> 
> Did you disable judging for some time during the test session (e.g. disable the judgehost or by an internal error)?
> 
> ![image](https://user-images.githubusercontent.com/418721/140323542-4b42e4c5-dea0-471d-9074-6c0c2abcbf79.png)

I think we added more judgehosts during the testsession, and 1 step for that is to pause all judgehosts.

**Comment by nickygerritsen** [comment]
Yep and during the contest we added even more. I felt like some Tobi guy stealing all hardware.

**Comment by mpsijm** [comment]
Let's see... If I remember correctly:
- Problem G has been removed and re-uploaded twice. The first re-upload was as problem ID 16 (which is now missing in the problems list), and I think this one happened during the test session. The second re-upload was after the test session. Because the old version of G (with ID 16) is now removed, could it be that this causes the missing data during that short time window during the test session?
- During the entire test session, we have had only one judge host running. Right before the contest started, we had six judge hosts. It could very well be that more judge hosts have been added during the contest, but during the test session we definitely had only one.

**Comment by nickygerritsen** [comment]
@mpsijm is right btw, during the test session we did not add any judgehosts.

**Comment by meisterT** [comment]
> The second re-upload was after the test session, as problem ID 19. Because the old version of G (with ID 16) is now removed, could it be that this causes the missing data during that short time window during the test session?

Indeed, that seems what was happening if I take the now deleted submissions into account:

![image](https://user-images.githubusercontent.com/418721/140414303-f73a6edc-d76e-4b9e-8cab-880c4bff9025.png)

You can see from the first few rows (that are an imperfect approximation of the judge queue sizes per team category) that there is definitely work to do that should be prioritized. I don't know yet why this would be happening. Perhaps best is to try this out and see if it reproduces. Unfortunately, we have lost initial priorities since we reset them on the first failed testcase.

**Comment by meisterT** [comment]
Well, well, look at this:
```
MariaDB [domjudge]> select * from queuetask where jobid >= 1998;
+-------------+--------+-------+----------+--------------+-----------+
| queuetaskid | teamid | jobid | priority | teampriority | starttime |
+-------------+--------+-------+----------+--------------+-----------+
|        2003 |    128 |  1998 |        0 |   1636106939 |      NULL |
|        2004 |    128 |  1999 |        0 |   1636106993 |      NULL |
|        2005 |      1 |  2000 |        0 |   1636107188 |      NULL |
|        2006 |      1 |  2001 |        0 |   1636107188 |      NULL |
|        2007 |      1 |  2002 |        0 |   1636107188 |      NULL |
|        2008 |      1 |  2003 |        0 |   1636107188 |      NULL |
|        2009 |      1 |  2004 |        0 |   1636107188 |      NULL |
|        2010 |      1 |  2005 |        0 |   1636107188 |      NULL |
|        2011 |      1 |  2006 |        0 |   1636107188 |      NULL |
|        2012 |      1 |  2007 |        0 |   1636107188 |      NULL |
+-------------+--------+-------+----------+--------------+-----------+
```

The first two are "normal" team submissions, the last are from an import. I guess we are getting back cached data somewhere.

**Comment by meisterT** [comment]
Ok, I have fixed the bug, but we could still allow to set a priority during import. I also want to add some tests but I have to think about how.

**Comment by nickygerritsen** [comment]
So I see two options:
* Add a field to the POST API and UI forms with the submission priority when uploading ZIP's
* Use a configuration setting like `jury_submissions_priority`

Any preferences? Maybe the second option is cleaner, since we don't have to change all places?

**Comment by RagnarGrootKoerkamp** [comment]
A global option with low priority default sounds simpler and good enough
I'd say.

**Comment by thijskh** [comment]
Does it need to be configurable? Or can we just always give them low priority?

**Comment by nickygerritsen** [comment]
Also fine by me if others agree
