### ISSUE TITLE
Support more fields when importing teams

### ISSUE THREAD

**Issue by shuibinlong** [DOMjudge/domjudge#1327]
When importing a team `.tsv`/`.json`, I found that the import interface does not parse the field of the team location, but it is necessary for tasks in many competitions.

The same as team members(in `.tsv`), team contests, even team comments?

**Comment by nickygerritsen** [comment]
Currently we advice to run a [CDS](tools.icpc.global/cds) if you need these. What is your use case to put them in DOMjudge?

**Comment by shuibinlong** [comment]
> Currently we advice to run a [CDS](https://tools.icpc.global/cds/) if you need these. What is your use case to put them in DOMjudge?

Maybe currently, we hope to have members and location information when viewing team details on the scoreboard page(when clicking one team‘s row).

And I searched the relevant code, and it seems that it can be achieved by adding some fields to the `importTeamsTsv` and `importTeamsJson` functions in `webapp/src/Service/ImportExportService.php`

**Comment by nickygerritsen** [comment]
> > Currently we advice to run a [CDS](https://tools.icpc.global/cds/) if you need these. What is your use case to put them in DOMjudge?
> 
> Maybe currently, we hope to have members and location information when viewing team details on the scoreboard page(when clicking one team‘s row).
> 
> And I searched the relevant code, and it seems that it can be achieved by adding some fields to the `importTeamsTsv` and `importTeamsJson` functions in `webapp/src/Service/ImportExportService.php`

I see the following issues with this:
* First, we (the whole ICPC world) is moving away from TSV to JSON, but that is fine. All these fields are also present in the JSON.
* We only have one field for location and one for members. How would you want to import these?
* For members this is in a different TSV/JSON, so you would need to import a separate file.
* Since both are only one field, it would be hard(er)/impossible to also expose this in the desired format in the API.

**Comment by shuibinlong** [comment]
> > > Currently we advice to run a [CDS](https://tools.icpc.global/cds/) if you need these. What is your use case to put them in DOMjudge?
> > 
> > 
> > Maybe currently, we hope to have members and location information when viewing team details on the scoreboard page(when clicking one team‘s row).
> > And I searched the relevant code, and it seems that it can be achieved by adding some fields to the `importTeamsTsv` and `importTeamsJson` functions in `webapp/src/Service/ImportExportService.php`
> 
> I see the following issues with this:
> 
> * First, we (the whole ICPC world) is moving away from TSV to JSON, but that is fine. All these fields are also present in the JSON.
> * We only have one field for location and one for members. How would you want to import these?
> * For members this is in a different TSV/JSON, so you would need to import a separate file.
> * Since both are only one field, it would be hard(er)/impossible to also expose this in the desired format in the API.

First, I agree that we will gradually shift the import interface tsv to the json format, so whether to add support for tsv is both fine for me.

Second, when I'm importing teams from a json file, I use `jury/import-export` page's JSON imput method, the json forma looks like the follows:

```json
}, {
  "id": "17",
  "icpc_id": "",
  "categoryid": ["3"],
  "name": "neolution 2.1",
  "display_name": "neolution 2.1",
  "members": "John, Joe, Anne",
  "organization_id": "1"
}, {
```

But I also need `Location` field which wasn't be parsed (I reviewed it from `webapp/src/Service/ImportExportService.php` 917L-934L). Even I think some other fields in the team table (such as `Comments` and `Contests` or `Penalty time` will also be needed in the future), so I think the `importTeamsJson` method needs to be enhanced.

**Comment by nickygerritsen** [comment]
> > > > Currently we advice to run a [CDS](https://tools.icpc.global/cds/) if you need these. What is your use case to put them in DOMjudge?
> > > 
> > > 
> > > Maybe currently, we hope to have members and location information when viewing team details on the scoreboard page(when clicking one team‘s row).
> > > And I searched the relevant code, and it seems that it can be achieved by adding some fields to the `importTeamsTsv` and `importTeamsJson` functions in `webapp/src/Service/ImportExportService.php`
> > 
> > 
> > I see the following issues with this:
> > 
> > * First, we (the whole ICPC world) is moving away from TSV to JSON, but that is fine. All these fields are also present in the JSON.
> > * We only have one field for location and one for members. How would you want to import these?
> > * For members this is in a different TSV/JSON, so you would need to import a separate file.
> > * Since both are only one field, it would be hard(er)/impossible to also expose this in the desired format in the API.
> 
> First, I agree that we will gradually shift the import interface tsv to the json format, so whether to add support for tsv is both fine for me.
> 
> Second, when I'm importing teams from a json file, I use `jury/import-export` page's JSON imput method, the json forma looks like the follows:
> 
> ```json
> }, {
>   "id": "17",
>   "icpc_id": "",
>   "categoryid": ["3"],
>   "name": "neolution 2.1",
>   "display_name": "neolution 2.1",
>   "members": "John, Joe, Anne",
>   "organization_id": "1"
> }, {
> ```
> 
> But I also need `Location` field which wasn't be parsed (I reviewed it from `webapp/src/Service/ImportExportService.php` 917L-934L). Even I think some other fields in the team table (such as `Comments` and `Contests` or `Penalty time` will also be needed in the future), so I think the `importTeamsJson` method needs to be enhanced.

For these JSON's we use the official CCS specification, see https://ccs-specs.icpc.io/draft/contest_api#teams.
As you can see it does not have comments, contests and penalty time. It does have location but it is an `x,y` pair. For members it has a [separate endpoint](https://ccs-specs.icpc.io/draft/contest_api#team-members), so that is also not just a string.

We *can* add our own fields, but they can not have the same name as a field from the spec. So what we could do:
* Add `comments` directly. The question is: what is the (read) permission for this field, can only admins see it?
* Add `penalty_time` directly. Same question: who can see it?
* Add `members` directly, but it might confuse people since members is also a thing in the spec (but using a different way).
* For `location` we could call it `room` (that's how it is called internally). Or name it something else, as long as it is not `location`.
* For `contests` I'm not sure what is best. We could add it, but from an API perspective it might be a bit odd: the API endpoints all reside 'below' a contest, e.g. `api/contests/1/teams/2`, so if you remove contest 1 from that team, does that mean you delete the team in the API? Also, what does the field actually contain? In our database it only contains the contests that are *not* open to all teams but this team does belong to (directly), but if you request the team using `api/contests/1/teams/2`, that would maybe be strange: don't you also want all contests open to all teams and the contests that this team belongs to indirectly (through their category)?

**Comment by eldering** [comment]
We discussed this and decided not to implement this location field.
