### ISSUE TITLE
`make inplace-conf` tries to build documentation when documentation is not requested

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1453]
When you provide additional options to the in-conf to not build the documentation the flag seems to be ignored. For an example of this see:

https://github.com/DOMjudge/domjudge-scripts/runs/5056135373?check_suite_focus=true#step:6:225

**Comment by nickygerritsen** [comment]
Seems to be because `inplace-conf` runs the `dist` target: https://github.com/DOMjudge/domjudge/blob/main/Makefile#L179
which runs the `distdocs` target: https://github.com/DOMjudge/domjudge/blob/main/Makefile#L43
which builds the docs.

I'm not sure if that is what we want. If not, we should somehow change `dist` to not run `distdocs` if you disable it, but my Make skills are -3 so no clue how to do it.
