### ISSUE TITLE
Possibity of adding extra steps for sent submissions

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1487]
Currently there is just:
- compile
- run
- compare

But possibility of adding extra step would be really helpful. E.g. commands:
1. style check
2. valgrind
3. anti-plagiarism check

I know that those sample can be done:
1. in `compile` step
2. in `run` step
3. after extracting data from database

IMO adding possibility of adding extra steps would be usefull not only at universities but also in many contests

**Comment by eldering** [comment]
How would it be helpful to have separate steps for this? Would a failure at one of these steps function differently than failing in the compile or run phase?

The reason I'm asking is because currently we have reasonably well defined interfaces for the compile, run and validation phase of a submission. Adding another phase (generic for all the above options, or even specific?) adds a good deal of complexity for the backend judging code.

**Comment by baziorek** [comment]
@eldering Thanks for Your answer. I'm using DOMjudge to check homework from students. Unfortunately students are trying to cheat and sending other's submissions after some simple modifications (variable names etc.).

Thats why it would be good to have possibility to run something which would run on all submissions. The sample tool is [Copy-Paste-Detector](https://pmd.github.io/pmd-6.41.0/pmd_userdocs_cpd.html).

Another step would be Valgrind to check memory leaks. Of course it can be used in `run` step, but I need to investigate.

**Comment by baziorek** [comment]
@eldering Making its separate step would make status cleaner. It would complicate system a little, but it would improve user experience:).

Another example of usage, which I see is code style check/static analysis - it can be done in `compile` step, but dirty code is not compilation error.

**Comment by baziorek** [comment]
@eldering Hi,
So what do You think about the idea? If You don't agree with the new feature I think the issue can be closed.

**Comment by eldering** [comment]
I don't really like it to be honest, as I think it will complicate the judging code with extra steps and associated logic that will only be used under circumstances that we'd barely if ever test during normal contests. That means that there'd be a high chance of of bugs that only occur under these or a mix of conditions to occur and quickly get noticed.
So I think it would be better to reuse any of the compile, run or compare steps for this, and then *if* it turns out that that really doesn't work for specific reasons, we can re-evaluate.

**Comment by baziorek** [comment]
I like honest people, thanks for honest answer:).
