### ISSUE TITLE
Password rules not enforced when importing accounts

### ISSUE THREAD

**Issue by brettreyno** [DOMjudge/domjudge#1560]
### Description of the problem
When creating a new user through the admin UI, version 8.0.0 requires that the password be a minimum of 10 characters long (possibly among other conditions, I haven't poked around with it much). These rules do not appear to be enforced when importing teams from a .tsv file; I generated a series of files with nine-character passwords, and they all imported successfully.

### Your environment
DOMJudge version 8.0.0
Amazon Linux 2.0.20200708

### Steps to reproduce

1. Create an accounts.tsv file as described in the manual
2. In that file, define passwords with a length of less than nine characters (mine used 3 upper, 3 lower, 2 numbers, 1 special, so unsure if other rules do/don't apply/exist)
3. Upload file to DOMJudge via API or import page

### Expected behaviour
Illegal passwords should be rejected, consistent with behavior in the "Add User" UI.

### Actual behaviour
Accounts are created with invalid passwords.

**Comment by vmcj** [comment]
This is by design,

We assume that the organizer has a good estimation if passwords should be easy to input for participants against the time it takes to bruteforce those if/when the domserver is public. So we prefer usability over security in this case.

Also for an password to be invalid it would need to not work, I think we only enforce the length when creating the user via GUI so after the password is saved (although short) it does work right? Otherwise that would be a bug.

**Comment by brettreyno** [comment]
I thought that might be the case, but wasn't sure. Thanks as always for the quick reply. :-)

And yes, the imported nine-character passwords are working, so I think everything's good here.
