### ISSUE TITLE
Add possibility to change colors of results in scoreboard and other places

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1579]
I'm academic teacher, who is using DOMjudge 7.3.4. I've suggested two nice-to-have features of DOMjudge, which were published in issue: https://github.com/DOMjudge/domjudge/issues/1578. I was suggested to split those two ideas into two issues.
_______________________
Sometimes students does not see different between compilation error and run error - this is red and this is red and of course "it is working in my computer". Even better students when they have run-error are trying to find compile-errors in warnings. Similar situation is when there is timeout, or crashes. It would be easier for them to see what is happening when there would be possibility to see different not successful reasons in different colors (currently there is only red or green). Also it would be easier for teacher to check submitted exercises when there would be different colors - currently in scoreboard I see red and I need to click always and check how many points should I give for a student. With colors when I see compiler error it won't be necessarily. I know that is is not much to click few few times, but there are about 200 students for single teacher, it would help much to have those colors:).
___________
So instead of:
![image](https://user-images.githubusercontent.com/15332594/168810440-8f506e81-e5d7-42fd-ae40-766e963fea7e.png)
I suggest to have:
![image](https://user-images.githubusercontent.com/15332594/168810488-db642ab8-5590-44c5-a964-0dcc4aba41c7.png)
__________
**What do You think about the idea?**

**Comment by vmcj** [comment]
Instead of extra colors I propose to add an icon for 2 reasons:
- Its hard to find colors which are distinct and are interpret as "wrong"
- Only doing an icon would remove the extra work of having to add a field to change the colors

Memory-limit https://fontawesome.com/icons/memory?s=solid
Output-limit https://fontawesome.com/icons/scroll?s=solid
Time-limit https://fontawesome.com/icons/hourglass-clock?s=solid
Correct https://fontawesome.com/icons/check?s=solid

When I have more time I can take a look if this is doable, unless you think we should do colors?

**Comment by baziorek** [comment]
For memory limit I suggest something else: https://fontawesome.com/icons/disc-drive?s=solid

For me both icons or colors are acceptable and would help really much!

**Comment by meisterT** [comment]
#1635 does neither add colors nor icons. We discussed in person today and decided that it would clutter the scoreboard/submission list quite a bit.

Note that as a team you only have a access to the binary correct/incorrect verdict status of other teams. For your own team it is clearly displayed on your submission page.

If you want to still change this in your own DOMjudge installation, I recommend customizing https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Twig/TwigExtension.php#L449.

The scoreboard would be quite hard to change since one cell may correspond to multiple attempts and in the scoreboard cache (that we eventually render) we only store if you a correct attempt or not, but not all the verdicts. So it would require rewriting a bunch of structures.
