### ISSUE TITLE
PHP Parse error:  syntax error, unexpected token "readonly"

### ISSUE THREAD

**Issue by rmecham** [DOMjudge/domjudge#1588]
### Description of the problem
> When attempting to run `bin/dj_setup_database install`, the following error occurs:
`PHP Parse error:  syntax error, unexpected token "readonly" in /opt/domjudge/domserver/lib/vendor/jms/serializer/src/Metadata/Driver/AnnotationDriver.php on line 109`

### Your environment
> Include details about your installation here.
> - DOMjudge version 8.0.0 (using the official tarball from the website)
> - Ubuntu 22.04 (freshly installed)
> - PHP 8.1.2
> - Apache

### Steps to reproduce
> Start with a newly installed instance of Ubuntu 22.04
> Follow the [DOMserver installation guide](https://www.domjudge.org/docs/manual/8.0/install-domserver.html) to the Database Configuration step

### Expected behaviour
> I expected the database migrations to run.

### Actual behaviour
> The script returned an error.

### Any other information that you want to share?
> I commented out the `set -e` line in the `dj_setup_database` script in order to see more diagnostic output.

**Comment by vmcj** [comment]
Hi @rmecham,

Thank you for reporting this, what you experience is because of the usage of PHP81 which DOMjudge8.0 does not support. I will create an update for the manual to make that more clear.

For now (I think) you have the following options:
- Run DOMjudge 8.0 with docker,
- Install against ubuntu20.04,
- Downgrade your PHP (I think thats a bit hard currently)
- Run our main branch, we've ran multiple contests with it and it works, but currently the UI is broken (due to an upgrade of the dependencies which didn't went as expected) so if you want this I propose you pick an older commit before that upgrade.

I'm not sure when DOMjudge8.1 will be released but I can bring it up if we can do this a bit faster to make DOMjudge on 22.04LTS possible.

If you need any help installing one of the options we can help you on our Slack (https://www.domjudge.org/chat) and I propose to close this issue if that is okay with you?

**Comment by vmcj** [comment]
DOMjudge 8.1 is now released so I'll close the issue.
