### ISSUE TITLE
ICPC export results.tsv wrong if multiple sort-orders present

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#180]
When the visible scoreboard contains multiple sort-order groups, then the export to an ICPC results.tsv file is incorrect since the rankings from the various  sort-orders are merged. So you might see multiple teams ranked 1, even though they do not have the same amount of problems solved.

I think we should ask for or/automatically select one sort-order and export only the team categories within that group.

**Comment by tomas-cerny** [comment]
Hi, ICPC web divides it so that by default the official shows up:

https://icpc.baylor.edu/regionals/finder/ctu-open-2015/standings

once you click on include unofficial then it shows the unofficial part as
well.

Two ranks cannot be uploaded and posted publically

**Comment by eldering** [comment]
Tomas, I assume this only works when the sort-grouping of categories used in DOMjudge matches with the team site grouping in the ICPC system. That is, we'd have to export a combined ranking which is the merge of precisely two rankings: one of eligible teams and one of ineligible teams.

In the export from the ICPC system, is there a way to see which teams and/or groups are considered ineligible? (I don't see that)

**Comment by tomas-cerny** [comment]
Hello Jaap,

the question is not correctly given. ICPC registration system does not
determine eligibility. We predict ineligibility, although it sounds like
two sides of the coin it is not. First, it is solely prediction not a final
decisions, next, each prediction could be false. Thus we only provide
information to contest manager of what she should check. The expected
process is that either the contest manager cancels registration or moves it
to unofficial (recently renamed to standalone) site. Thus considering that
there are multiple sites where one is dedicated to ineligible teams
(standalone type) and I believe exports give you the site a team is at, so
that should be the indicator. Considering the above the eligibility should
not be considered in any CCS, solely the membership of a particular site
that is standalone or other (counts towards ICPC reports).

Let me know if this works.

Tom

**Comment by eldering** [comment]
Hi Tom,

Maybe I don't completely understand your answer, but I'm still left with
the question: how is it determined which sites correspond to
(provisionally) ineligible teams (i.e. standalone sites)?

Does there exist a flag in the ICPC system that a particular site
contains ineligible teams? And could there be multiple such sites? If
so, how can this be inferred from TSV files exported from the ICPC system?

If no such information is stored in the ICPC system, then how do you
determine which sites contain the ineligible teams, when the results TSV
files are uploaded into the ICPC system?

It would be really helpful if you could point me to explicit fields in
the TSV files specifications [1] and the ICPC CMS API [2] that I can
use, either when importing or exporting data.

Best,
Jaap

[1]
https://clics.ecs.baylor.edu/index.php/Contest_Control_System#Appendix:_File_formats
[2] https://icpc.baylor.edu/community/cmsinterface

**Comment by tomas-cerny** [comment]
Hello,

>Maybe I don't completely understand your answer, but I'm still left with
the question: how is it determined which sites correspond to
(provisionally) ineligible teams (i.e. standalone sites)?

There is not an answer.. since any contest manager can apply any strategy.

Generally what is in a standalone sites does not count to ICPC reports and
statistics and also from a standalone site cannot team qualify to finals or
be promoted.
So usually standalone site is used for teams that are not official -
regards to ICPC qualification for super contest.

At the same time contest manager can leave clearly ineligible team in
normal site and just not to promote to super contest.

>Does there exist a flag in the ICPC system that a particular site
contains ineligible teams? And could there be multiple such sites? If
so, how can this be inferred from TSV files exported from the ICPC system?

Sites are of 3 types - Normal / Administrative (both technically the same)
and Standalone (formally unofficial).. There is no limit on the total
amount of sites.
There are exports for CCS that contain site information - not its type.

> TSV files exported from the ICPC system
Which export specifically do you suggest to contain it..there are multiple?
The issue might be with other CCSystems that may use the format.

Or u may use Webservices that contains it
https://icpc.baylor.edu/ws/myicpc/contest/{contest key}/sites

>If no such information is stored in the ICPC system, then how do you
determine which sites contain the ineligible teams, when the results TSV
files are uploaded into the ICPC system?

Site type [normal,administrative,standalone]

Site contains teams
Contest contains sites

Teams in Standalone site are not in official scoreboard.

But the Term ineligible is distinct from the concept.

>It would be really helpful if you could point me to explicit fields in
the TSV files specifications [1] and the ICPC CMS API [2] that I can
use, either when importing or exporting data.

I would suggest to use this:
https://icpc.baylor.edu/community/cmsinterface

consider https://icpc.baylor.edu/community/cmsinterface#HContestsites

The exports here:
[image: Inline image 1]

These only contain site name and site ID (some call it group), which is
used to determine team membership.

If you point the one u use for import I can see whether we can add it.

Tom

**Comment by eldering** [comment]
Ok, so the site type (normal/administrative or standalone) is what's
relevant: this determines the scoreboard split in the ICPC system. It
means that we should export a scoreboard with at most two sort-orders,
where sites/groups (or team categories in DOMjudge terminology) are
grouped in a "normal"/"administrative" group and a separate "standalone"
group.

We support both im/export via TSV files and via the CMS API, so ideally
I'd like to be able to get the site type via both ways. I understand
that currently this information is only provided via the CMS API, not
via TSV files. It would be great if this site type information would
also be available in some way in the TSV files; I have no preference
precisely where.

**Comment by tomas-cerny** [comment]
I will add the request on TSV  to be processed and will get back to you one
deployed.

Tom

**Comment by eldering** [comment]
@tomas-cerny any update on this?
