### ISSUE TITLE
Split access log between API and other requests for Apache 

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#1856]
In #1833 the access logs for nginx were split between API and other requests. We should also do this for the apache config.

I think this is relatively simple for someone who uses Apache to contribute an implementation for this.

**Comment by nickygerritsen** [comment]
It seems this is not possible for the 'alias' way of doing things (i.e. under /domjudge) at all, since CustomLog and ErrorLog are only allowed in server or virtualhost blocks. For a virtual host we can use a custom log, but not a separate one for the API log.

So I propose to close this issue and only support this for nginx.

**Comment by vmcj** [comment]
Alternatives would be:
- https://httpd.apache.org/docs/2.4/programs/split-logfile.html (which to me also shows that there is not a builtin solution)
- Log to a custom binary/service and split there (https://serverfault.com/a/1018620)

I agree with closing,
