### ISSUE TITLE
[Discussion] Consider using some (MVC) framework for the web-interface and API?

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#198]
While talking to @tuupke about some DOMjudge ideas (mainly for the still WIP online judge rework thingy of us), we ended up in a discussion about why we are not using some framework for the web interface and API.

I partially know the answer myself (no experience and it grew this way), but I think we should start considering it. Last weekend during the hackathon our great friend Jan already noticed the current code is mixing UI and controller code like it's nothing. This worked for simple pages, but we are getting more and more complex pages, like the testcase page. Jan started working on trying to get Twig integrated for that page, but perhaps we should move it a step further and use some framework like Symfony or Laravel (or another one...).

I think the web interface and API of DOMjudge are not too difficult: I think the difficult part is in the judgedaemon and related things.

This issue is to discuss whether we even see this as an option :).

To start of some discussion, let me add some advantages and disadvantages which I see.

Advantages:
- We can use the strong base of a framework to do a lot of stuff. For example a framework has a coupled templating engine, database wrapper, etc. lib.database.php served us well for a long time but I think for most things some ORM would make more sense.
- It is easier for (external) developers to add code, because we use some (well-known) setup.
- Separating UI and logic is a thing we already want to do and a framework will almost force us to do so automatically.
- Doing something like the API we currently provide is almost trivial in a good framework.
- So is doing authentication.
- We can lift upon (security) updates from the framework.

Disadvantages:
- There are some queries for which an ORM is maybe hard. I can image some of the scoreboard things to be hard. However, normally we could bypass the ORM for some specific things. Or for example Doctrine ORM allows you to write ORM-style selectors which are a close mapping to an SQL query.
- It will be quite some work to do this: it won't be something we can do in a week. We need to rethink and/or rewrite a lot of our code.
- During the "transition period" we will add features using the current structure which we need to re-do when the transition is complete.

Some might think the performance will drop using a framework. However, I don't believe this is the case for a good framework. Frameworks nowadays have a lot of mechanisms to have no or only a little performance impact and I think that using a framework will even speed up some things, because the framework can already have good support for caching stuff etc.

What do other people think about this idea?

I don't want to really discuss which framework etc. yet, as I think we first need to decide whether we want to use it at all.

**Comment by eldering** [comment]
First of all, I don't have any experience with PHP frameworks nor with templating, so writing from that perspective.

I think indeed the main point in deciding whether to use a framework (and which one) is whether it makes the code easier to develop/maintain, both for current developers and new contributors. I think the current code for webpages is not always clear, especially since it mixes logic with presentation. Clearly a template system will help there, but most of the logic is fairly straightforward and understandable.

Secondly there are some home-grown solutions to abstract away e.g. form building, DB relations and data validation, etc. I think these are the most difficult to understand from the point of view of a new contributor (and sometimes even to me ;-) On the other hand, a PHP framework also adds an extra layer of abstraction, which even though standard, has to be learned too. Therefore, I think the most important questions here are:
- Is it possible in the framework to express (nearly) all logic that we currently use?
- How easy is it to write customized code for things that don't fit inside the framework?
- How much unncessary abstraction does the framework add?
- How many extra dependencies does the framework add, i.e. does it run on latest Debian/Ubuntu stable (LTS) releases?

So I think a framework could be a good choice, but it may depend a lot on the details of the framework (again, I don't know these frameworks, so cannot judge this). In particular, I'd be interested to see how some of the more complex DB queries could be handled within a framework and whether on these the performance is still acceptable.

So my proposal would be to investigate which framework(s) would suit us best and then choose one or two pages with complicated logic and try implement these inside the framework.

**Comment by nickygerritsen** [comment]
> I think indeed the main point in deciding whether to use a framework (and which one) is whether it makes the code easier to develop/maintain, both for current developers and new contributors. I think the current code for webpages is not always clear, especially since it mixes logic with presentation. Clearly a template system will help there, but most of the logic is fairly straightforward and understandable.

True about easy logic. I indeed think separating those will make sense for new devs.

> Secondly there are some home-grown solutions to abstract away e.g. form building, DB relations and data validation, etc. I think these are the most difficult to understand from the point of view of a new contributor (and sometimes even to me ;-) On the other hand, a PHP framework also adds an extra layer of abstraction, which even though standard, has to be learned too.

True, but then at least you can Google for questions instead of needing to read the contents of lib.database.php or edit.php ;-).

> Therefore, I think the most important questions here are:
> * Is it possible in the framework to express (nearly) all logic that we currently use?

I think we should somehow find out what the hard parts of our logic are so we can try to understand how to implement this in a framework.

> * How easy is it to write customized code for things that don't fit inside the framework?

This of course depends on the framework. Also, we need to know what doesn't fit in it.

> * How much unncessary abstraction does the framework add?

I think this is something we can only find out when trying frameworks. Also sometimes it is not too much of a problem if it adds abstraction, as long as it makes some sense and doesn't impact performance, etc.

> * How many extra dependencies does the framework add, i.e. does it run on latest Debian/Ubuntu stable (LTS) releases?

Yup we at least need to check this.

> So I think a framework could be a good choice, but it may depend a lot on the details of the framework (again, I don't know these frameworks, so cannot judge this). In particular, I'd be interested to see how some of the more complex DB queries could be handled within a framework and whether on these the performance is still acceptable.
> So my proposal would be to investigate which framework(s) would suit us best and then choose one or two pages with complicated logic and try implement these inside the framework.

The only framework I work with regularly is Symfony. For this I can already answer some questions:

* Version 2.8 (latest LTS) requires PHP 5.3.9+ and JSON and ctype need to be enabled, according to http://symfony.com/doc/2.8/reference/requirements.html. 3.0 (latest normal release) required PHP 5.5.9+.
* Symfony is in its core a list of useful smaller projects bundled together, which can help in not using unneeded abstraction. They offer a "default set" of stuff which normally makes sense, but they also have a REST-API set of stuff for example.
* They use Twig for rendering and Doctrine as an ORM. Most simple-ish queries are easy to do in Doctrine and you can write something similar to SQL for complex queries. More on database-stuff below.

About the DB queries: because the database ORM for most frameworks is pretty self-contained, we could first try to do one or more complex queries in the ORM. I would be willing to try this for Doctrine, but then we should maybe figure out some complex queries :-).

I am curious whether other people have experience with other frameworks btw. Or bad experiences with Symfony.

**Comment by tuupke** [comment]
Since I was mentioned in the original question I feel I should also respond. Even though I have never directly contributed to dj.

For me the issue with starting to develop on dj is the (perceived) high level of knowledge required to start. Since many features are split over multiple files and are loaded in a (sometimes) odd order. Personally, deciding what needs to be changed where in order to implement a feature while making sure nothing else breaks is a huge task and nigh impossible, in my opinion.

Having a framework which (semi) forces you to work using a certain design pattern alleviates this entire issue. @nickygerritsen basically summed it up pretty good. Most frameworks provide some database abstraction using an ORM, provides some form of templating, and maybe even more important: gives access to libraries with implementations. So new features do not necessarily have to be implemented since an "off-the-shelf" solution is available. Or the library at least has the basics covered.

On the choice of frameworks. Personally I have much (positive) experience with Laravel & Lumen and bad experiences with Doctrine (the ORM of Symfony). Mainly since DQL (the SQL dialect used in Doctrine) has no support for some common features of SQL like unions and excepts. But many, many frameworks exist some provide high levels of abstractions and force you to work in some manner (like Laravel and Symfony) while others are more "flexible" (like Slim) but all provide basically the same feature set. 

> * How many extra dependencies does the framework add, i.e. does it run on latest Debian/Ubuntu stable (LTS) releases?
That is one of the exact issues these frameworks have to deal with, therefor new versions of these frameworks always require php versions which are in the (latest) stable versions of common server operating systems. 

Another options could be to self-implement a framework, but then in a few years dj would end up in the situation where it is now.

All in all I think there are way more advantages then disadvantages. it would lead to a more maintainable project. While also being accessable for new contributors since they can use a structure and default tooling (like composer) which they are used to.

**Comment by nickygerritsen** [comment]
What @tuupke says is quite true I think; he often texts me about how to do stuff in DOMjudge, because it currently is not really in a logical place.

I myself have no Laravel / Lumen experience and have not had problems with DQL yet. But I haven't tried doing a UNION or EXCEPT query in it. I did do a little grep on the code and we do not use UNION / EXCEPT currently. I'm also guessing (not sure because I'm no SQL pro) that those two are not ideal to use in MySQL as it will probably use temporary tables for them.

Anyway, I'm not opposed to any framework currently but I do think it would make sense that we use one that at least someone in the team has experience with.

**Comment by jbransen** [comment]
Yes, this is a good idea. I've been thinking about this for a while and I believe with the introduction of the API, the codebase has reached the point where using some abstractions is really necessary to keep the code maintainable.

I think there are two important improvements to make:
1. Using some ORM to abstract over all database queries
2. Use some templating system to separate the HTML from the PHP code

There are frameworks that can do both (and much more), and I am not sure if that is a good idea. As @eldering points out framework can cause unnecessary abstractions. I would suggest to tackle both points (sort-of) separately, and drop the idea of using a big framework to do this all at once.

The main motivation is that the transition can then be done easily. When introducting an ORM the database queries can slowly be rewritten over time, and the same holds for the front end pages. Of course the choice for the concrete frameworks/design patterns for this is then still open.

**Comment by nickygerritsen** [comment]
I think for the first part this can be a valid approach, but if we only introduce a templating engine for the views, we still have a lot of PHP code that are now put in "some" lib-files, edit.php for (almost) all form submission handling, etc.

For me this feels as almost a big a mess as the mixing of the view-related code and PHP. Using templates only will not really solve that part I guess. It is nice that then the real view-related code is separate, but in I think this is only a part of the solution.

However, we might also tackle that point (a lot of shared code everywhere) separately from the first two, although I do think that in the end you then again end up with either something that is very similar to some framework but not understandable for a "DOMjudge noob" or actually a real framework.
Not sure though.

**Comment by nickygerritsen** [comment]
After thinking a bit more about this in bed (....), I'd like to change my previous opinion:

Although first using a ORM for the database queries solves one part (not needing to do `SELECT * FROM...` everywhere), I think it does not solve my (and I think also @tuupke's) main concern that the code will stay "messy" and "homegrown" if we use this approach. For me this is a bigger problem than having SQL queries in the code and I think @tuupke also means this: if we use some "standard" framework it is way easier for others (and us too) to "get into" DOMjudge and add features.

**Comment by eldering** [comment]
My feeling is that to get this discussion forward, we should start looking into choosing a specific PHP framework and try to implement things to see how it would work.

As already mentioned (not sure in this thread) I think we should choose a framework that at least some of the active developers are familiar with. Further, it would be good if the framework is modular so that we can start rewriting code for templatiing, ORM, and other things in separate phases. It sounds to me that Symfony does fit these requirements, while the objection of not supporting UNION and EXCEPT is not relevant for the current code. Also, Jan started reimplementing the testcase page in Twig. Any (new) arguments for/against using Symfony to start an implementation test?

**Comment by nickygerritsen** [comment]
To add something here: I tried a really small test last sunday where I imported our database scheme in Doctrine (Symfony's ORM) and that seemed to work quite nice.

Within a few moments I could write

```twig
{% for user in users %}
  {{ user.uisername}} {{user.team.name}}
  {% for role in user.roles %}
    {{ role.role }}
  {% endfor %}
{% endfor %}
```

Without writing a query :-).

Of course users are quite simple in our database and stuff like the scoreboard will be a bit more complex.

**Comment by nickygerritsen** [comment]
Btw perhaps we should make a list of a few things we would like to see how they work in a framework, so we can focus on that. For example:

* A simple page for managing an entity, i.e. a user and/or team
* A more complex page?
* An API action
* Some complex query-thingy?
* etc.

I think we could start with just creating a separate repository for testing purposes where we do some of these things.

**Comment by tuupke** [comment]
If there is a plan to start doing this, I'd love to start helping out, as stated before I've had many things I wanted to implement (and have implemented) in dj, but never felt it was good enough (or well tested enough) to submit a pr.

For the people that are interested, [http://socialcompare.com/en/comparison/php-frameworks-comparison](this page) contains an extensive comparison of many popular frameworks.

**Comment by eldering** [comment]
Ok, I've created a new branch `framework-rewrite` on top of current master. Feel free to experiment in there!

I also invited @tuupke as a member, so you can commit directly to the repository.

**Comment by nickygerritsen** [comment]
OK I'll try to see if I can do some experiments in Symfony, but maybe @tuupke wants to look at (an)other framework(s)? Maybe it makes sense to make a different branch for each, but I guess I can do that myself.

**Comment by tuupke** [comment]
@eldering Thanks!

@nickygerritsen Mhh, what do you propose to do experiments on? What do you want to find out specifically?

**Comment by nickygerritsen** [comment]
That's why my list was there. I gues Jaap or someone could extend the list?

**Comment by eldering** [comment]
I found this [comparison between between Symfony and Laravel](https://www.reddit.com/r/PHP/comments/1bdln1/symfony2_vs_laravel) useful. It makes me tend to prefer Symfony for greater flexibility in choosing which parts to use and flexibility over simplicity/convention.

**Comment by nickygerritsen** [comment]
Note that that post is 2 years old. I'm not sure if Laravel still has the same way of working (although I can imagine as the author of Laravel was one of the commenters and I could imagine he doesn't just change his ideas)

**Comment by meisterT** [comment]
:+1: to the full thread

After several years of DOMjudge development, I fully agree that these changes would help us to achieve a cleaner code base as well as attract more contributors.

Before we make a decision I'd like to see how the frameworks perform when joining a couple of tables with a lot of data in them. As an example for a good test: reimplement the submission page and display the test verdicts from the judging_run table for a problem with *many* test files and megabytes of input and output. These data is meant to be displayed directly on the page, but some ORMs I have worked with in the past did fetch all tables instead of only fetching the relevant tables.

**Comment by nickygerritsen** [comment]
@meisterT do you have a database dump I could use for that?

And what do you mean with all tables vs relevant tables? Which tables are not relevant?

**Comment by meisterT** [comment]
urx, s/tables/columns/, i.e. input and output are stored in the same table as the verdict but not displayed by default but available for download.

Regarding database dump: sorry, no, but you can just add the same test case many times.

**Comment by nickygerritsen** [comment]
That makes more sense yes. I'll try this :)

**Comment by nickygerritsen** [comment]
Related: http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/partial-objects.html

I think for Doctrine this is the solution to that problem but will try it IRL

**Comment by nickygerritsen** [comment]
I pushed my first changes to the branch. I made small commits so everyone can see what I have done.

It doesn't have the submission(s) page yet, but I created a lot of basis: 

* I imported the database in the ORM
* You can already log in with the users from the database
* There are /public, /jury, /team and /api paths, where the jury and team paths already have correct security checks
* There are menu's, where almost all entries have no link yet, except for the ones linking to other parts (i.e. from /team to /jury)
* The contest-data in the topright is acurate. At least it should be ;). I used a service for this, so you can call this service from where you want if you have a DI aware class. I exposed the service for Twig templates. The contest-data is different for each sub-part, like it used to be. The base.html.twig for each part defines what the contest data is
* There is a Twig function to render a time diff, which I currently use for the contest countdown. The javascript updateClock function is just copied from the current site, as is the rest of the javascript and CSS

To run it locally and check it out, the following should be sufficient:

* Download composer
* Run `composer install`
* It will ask for database settings. Also for some mailer settings which we do not use (yet?) and a secret. Choose something for the secret, doesn't really matter (cookies are encoded with it). Finally the domjudge version, which I locally have set to `5.2.0DEV`
* Now run `app/console server:run` and you can visit http://127.0.0.1:8000 and try to log in

Next on my list is the submissions page and a specific submission. But now it is time to sleep :).

Note that there are at least some things I left out for now:

* Nicer looking forms. This is easy doable with a form-theme but doesn't really matter for the experiment I guess
* Translations. This is easy to do in Symfony but for now strings are hardcoded

What do you guys think of it thus far? I'll try to be on IRC tomorrow (afternoon) and sunday (whole day) if you have any questions.

**Comment by nickygerritsen** [comment]
OK I completed the submissions detail page yesterday (with some TODO's for some forms, etc.).

Today I added the team management page almost completely. It is only missing the user-create-upon-team-create.
I think this team-management page really shows some of the niceness of a framework and in particular Symfony. The edit and create pages use the same form type, which both use annotations on the model to describe the constraints.

For me I guess the experiment is now at least worked out enough for Symfony, as I've created both a complex page and a "simple" CRUD controller.

For the API we can simply add some extra auth type (e.g. HTTP basic auth) and add controllers that output JSON, etc. (or use a bundle like FOSRestBundle but that's maybe too advanced for us).
For importers / exporters you can easily add command to the `app/console` script that can use services, models, etc.

So I'm not sure how to progress now. We should either do something similar with other frameworks, decide we want to use Symfony, or decide frarmeworks are not it after all.

**Comment by tuupke** [comment]
@nickygerritsen great work, looks awesome!

Me myself, I've had a lot less time available then initially hoped. But am currently working on the same thing's in Laravel, hopefully have something to show somewhere early this week. But from what I understood from meisterT's comment the team pages etc. might be more then needed. When I'm done with purely the submissions, I'll push my progress (and submit a comment with some instructions) and continue on to another framework. Or (iff required) implement some more simple things as well.

**Comment by meisterT** [comment]
@tuupke any update on Laravel?

**Comment by meisterT** [comment]
We had an offline discussion and decided to move forward with symfony. We do not want to rewrite DOMjudge from scratch, so we decided to do a gradual transition. As one of the first steps, we already started using composer for dependency management. Next step is probably to integrate twig.

**Comment by nickygerritsen** [comment]
Cool! Wasn't Jan trying to do that at some point?

**Comment by eldering** [comment]
Yes, he started a rewrite of the jury/testcase.php in Twig. I'm attaching

[twig-testcase.zip](https://github.com/DOMjudge/domjudge/files/299508/twig-testcase.zip)


 his files.

**Comment by eldering** [comment]
The jury testcase and judgehost pages have been rewritten using Twig.

This probably can still do with some cleanup; also, there are plenty of pages left to do.

Help very welcome!

**Comment by eldering** [comment]
As a progress report, we've started using more of Symfony, including the Doctrine, the ORM layer, and the routing and controller parts. We still have a legacy controller in place and are slowly transitioning.

**Comment by thijskh** [comment]
I think this item is complete in the sense that the discussion has been had, our direction on this is clear and implementation is well under way. There are a few remaining items to be migrated but they are on our radar.

**Comment by eldering** [comment]
Agreed, so closing this. Feel free to reopen if there is still a significant discussion to be made.
