### ISSUE TITLE
Download of scoreboard fails when non-public contest

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#2060]
### Description of the problem
The jury UI has the option to download the static scoreboard. The FPC jury uses this to compare the different sites to make a set which is accessible for all sites.

### Your environment
> DOMjudge: main somewhere last week

### Steps to reproduce
> Go to demoweb, set the nwerc18 contest to non-public
> Go to `https://www.domjudge.org/demoweb/jury/contests/7`, observe that the admin interface has the option to download the scoreboard (which will fail)
> The link goes to https://www.domjudge.org/demoweb/public/scoreboard-data.zip?contest=7, this is under `/public` which should not allow this zip due to the setting no `/public` scoreboard.

### Expected behaviour
> Either the button is not there when non-public, or its grayed out, or we add some logic to do allow this when you're an admin. Maybe moving this away from `/public` is smarter to keep that code simpler.

**Comment by mpsijm** [comment]
There are also multiple versions of the scoreboard: one is `/jury/scoreboard`, and one is `/public`. I guess you could do the same with the zips :slightly_smiling_face: 

The only difference is: I would expect that the export still only shows the public teams, even when accessing the jury-authenticated endpoint, because that's what we want for the archives. Or have two different kinds of export: one that only shows the public teams, and one that shows all teams.

**Comment by nickygerritsen** [comment]
Given that the ZIP is publicly accessible, we DO need the existing ZIP. I'm cooking something up 🧑‍🍳
