### ISSUE TITLE
Time format not accepted

### ISSUE THREAD

**Issue by Abdelghafour01** [DOMjudge/domjudge#234]
The default time format is not accepted while creating a new contest:
![image](https://cloud.githubusercontent.com/assets/17223744/18793560/cf327394-81aa-11e6-9c18-0d1b26c79c06.png)

**Comment by eldering** [comment]
Hi, I cannot reproduce this. Which version of DOMjudge and which O/S and browser+version are you using? Can you try in one or two other browsers?

**Comment by corneym** [comment]
I too have been seeing this on Domjudge/5.1.1 using Chrome 53.0.2785.116.  The behaviour does not repeat in Firefox 47.0.1 or on Internet Explorer 11.0.9600.18449

**Comment by eldering** [comment]
Ok, I think I fixed this Chrome specific issue (I could reproduce it with Chromium on Debian Jessie). Please see the fix in the referenced commits.

**Comment by gjigandi** [comment]
Thanks for pointing this out. It was driving me crazy.
I am using DOMjudge 5.1.1 on Mac OS X with Google Chrome 53.0.2785.116.
I have always used Google Chrome to create the contests without any problem. Only recently, when I tried to update one of the contests to postpone it the error appeared.
I confirm that using Safari everything went smooth.

I haven't pulled the fix for Chrome yet but thanks for fixing it.
