### ISSUE TITLE
Add configuration option to make disallow answering clarifications without claiming

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#2481]
Currently claiming a clarification is purely decorative and doesn't enforce anything. The jury at the finals requested to make it actually impossible to reply to a clarification which is claimed by another jury member. 

This could be a configuration setting.

**Comment by thijskh** [comment]
Is the issue that people replied to things they didn't notice were claimed by someone else? Would it already be helpful to have a warning at the reply box: "You are now replying to a claification claimed by X"?

**Comment by meisterT** [comment]
Multiple jury members answered the same clarification. So a dialog like you propose that checks for whether the question has been claimed or answered sounds useful.

**Comment by as6325400** [comment]
It seems like this issue hasn't been resolved yet?

I think we could add a 'strong claim' option.

This option would prevent other jury members from responding.

And for regular claims, we could add an additional alert notification, just like mentioned above."

**Comment by eldering** [comment]
I don't think a "strong claim" option is great, since we always allow someone to respond to a clarification, even if a response has already been sent. So blocking that would require adding extra complexity.I think @thijskh's suggestion would be good enough to prevent people from answering inadvertently, both if the clarification was claimed or replied to in the mean time.
