### ISSUE TITLE
Add head judge role

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#249]
Add option to restrict sending out clarifications (and rejudgings?) to one person, namely the head judge.

**Comment by eldering** [comment]
In this case, what about giving the head judge the admin role and adding a config option that this requires admin rights? I'd prefer to keep the number of different roles as small as reasonably possible, to keep the code simpler and also not lose oversight of what roles have which privileges.
Minor quibble: I don't think the `CCS compliant` milestone applies: this is not part of the [CCS spec](https://clics.ecs.baylor.edu/index.php/Contest_Control_System), or is it?

**Comment by eldering** [comment]
I propose that we simply add two configuration options to toggle whether jury members or only admins can send clarifications or perform rejudgings.

**Comment by thijskh** [comment]
I disagree: we have roles to provide a way to confiure what rights a user has. If we then also add configuration that changes the meaning of a role, I think stuff becomes more compex rather than less.

If you have to combine checking for roles with checking for config setting, that creates more complex conditionals.

**Comment by thijskh** [comment]
Would it only be sending (and composing I presume)?
More precisely: shpuld other jury members still be able to:
- claim clarifications
- mark clarifications as answered
- change categories
- change queues
