### ISSUE TITLE
Keep balloon order stable across page refreshes

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge#260]
The current workflow for balloons is to have a staff member look at the balloon page, deliver the balloon (or give it to another staff for delivery), then mark "Done".

This causes a race condition: it's possible for the page to refresh just before the staff member hits "Done", and if there are new balloons, the click will hit the "Done" button of another balloon than what was intended, because the intended balloon is now further down the page.

I think [ordering balloons by ID ASC rather than DESC](https://github.com/DOMjudge/domjudge/blob/master/www/jury/balloons.php#L195) would fix this.

**Comment by eldering** [comment]
I agree that the order of unprocessed balloons should be reversed. This also makes sense from a use-case perspective: oldest balloons are then at the top, and these should be dealt with first.
However, I think that processed balloons should be in descending order. I think this can be fixed by setting `ORDER BY done ASC, (1-2*done)*balloonid ASC`. Comments?

**Comment by SolalPirelli** [comment]
Keeping the already-done balloon in "most recent first" order seems good indeed, that formula should work well.
