### ISSUE TITLE
Importing a problem archive fails when another archive with the same name has already been uploaded

### ISSUE THREAD

**Issue by machitgarha** [DOMjudge/domjudge#2633]
### Description of the problem

When importing a problem via an archive, if the uploaded zip has a name that another zip with the same name had been uploaded, then it leads to the following weird error:

```
Array
Array
Array
```

### Your environment

DOMJudge version: 8.2.3
OS: Fedora 36 (Server edition)
Platform: Docker
Webserver: Nginx

### Steps to reproduce

- Create two distinct problems, both with the same name (i.e. `A.zip`).
- Import the first problem archive.
- Import the second problem archive.

### Expected behaviour

Both problems get uploaded.

### Actual behaviour

The first one is imported successfully, but the second one fails with the error above.

### Any other information that you want to share?

There is a similar question [here](https://github.com/DOMjudge/domjudge/issues/1708), but it doesn't seem to be this specific.

**Comment by cubercsl** [comment]
![image](https://github.com/user-attachments/assets/61fc659d-be5c-443e-9a57-c7f88b2f07bc)
I'm trying to reproduce this on the main branch.

If you don't specify a problem externalID in `domjudge-problem.ini` in you `A.zip`, the file name will be used as the externalID, and externalIDs must be unique. 

https://github.com/DOMjudge/domjudge/blob/8.2.3/webapp/src/Service/ImportProblemService.php#L134-L143

The import failure is by design. But the weird error is a bug.

**Comment by cubercsl** [comment]
I think this is caused by

https://github.com/DOMjudge/domjudge/blob/6a916416463852c007a2f1a0a2de5a2287cc6158/webapp/src/Controller/Jury/ImportExportController.php#L183-L189

which passes the wrong parameter, it should be

```patch
diff --git a/webapp/src/Controller/Jury/ImportExportController.php b/webapp/src/Controller/Jury/ImportExportController.php
index f1fa4f9b8..20e14fd4c 100644
--- a/webapp/src/Controller/Jury/ImportExportController.php
+++ b/webapp/src/Controller/Jury/ImportExportController.php
@@ -184,7 +184,7 @@ class ImportExportController extends BaseController
                     $this->dj->auditlog('problem', $newProblem->getProbid(), 'upload zip',
                         $clientName);
                 } else {
-                    $this->addFlash('danger', implode("\n", $allMessages));
+                    $this->addFlash('danger', implode("\n", $allMessages['danger']));
                     return $this->redirectToRoute('jury_problems');
                 }
             } catch (Exception $e) {
```

But this has been fixed since https://github.com/DOMjudge/domjudge/commit/a6640d5a5f9357cb0c41d2b51811524efe1fb567

**Comment by vmcj** [comment]
> I think this is caused by
> 
> https://github.com/DOMjudge/domjudge/blob/6a916416463852c007a2f1a0a2de5a2287cc6158/webapp/src/Controller/Jury/ImportExportController.php#L183-L189
> 
> which passes the wrong parameter, it should be
> 
> ```diff
> diff --git a/webapp/src/Controller/Jury/ImportExportController.php b/webapp/src/Controller/Jury/ImportExportController.php
> index f1fa4f9b8..20e14fd4c 100644
> --- a/webapp/src/Controller/Jury/ImportExportController.php
> +++ b/webapp/src/Controller/Jury/ImportExportController.php
> @@ -184,7 +184,7 @@ class ImportExportController extends BaseController
>                      $this->dj->auditlog('problem', $newProblem->getProbid(), 'upload zip',
>                          $clientName);
>                  } else {
> -                    $this->addFlash('danger', implode("\n", $allMessages));
> +                    $this->addFlash('danger', implode("\n", $allMessages['danger']));
>                      return $this->redirectToRoute('jury_problems');
>                  }
>              } catch (Exception $e) {
> ```
> 
> But this code has been refactored and fixed since [a6640d5](https://github.com/DOMjudge/domjudge/commit/a6640d5a5f9357cb0c41d2b51811524efe1fb567). We need to cherry-pick to 8.2 or make corresponding fixes.
> 
> cc @meisterT.

@cubercsl are you willing to PR this?

**Comment by machitgarha** [comment]
Thanks for the quick fix!

@cubercsl, is the externalID already documented?

**Comment by cubercsl** [comment]
> Thanks for the quick fix!
> 
> @cubercsl, is the externalID already documented?

It has already been implemented in the code (i.e. your archive basename will be used as external ID), but  this is not mentioned in the documentation.
https://github.com/DOMjudge/domjudge/blob/f5d8b155a9e7e1baa4251aef1086dcf085ed24f9/webapp/src/Service/ImportProblemService.php#L134-L143


BTW, the documentation doesn't mention that we can set `problem.externalid` and `contestproblem.shortname` in `domjudge-problem.ini` since https://github.com/DOMjudge/domjudge/commit/e316344c6faa2317e951e39985cab0f371d96358.

https://github.com/DOMjudge/domjudge/blob/c01749d0d26be81d98ed1dd68c49df397c590028/doc/manual/problem-format.rst?plain=1#L31-L46
