### ISSUE TITLE
Avoid getting stuck with lack of disk space

### ISSUE THREAD

**Issue by iriszero** [DOMjudge/domjudge#278]
Domjudge may eat the last byte in the disk and it makes the administrator can do almost NOTHING for recovery because Domjudge has been taken the last byte for the pipe operations. It can be avoided if the Domjudge or Judgehost create a dump file with proper size (i.e. 16MB) at the beginning, remove it after detecting the lack of space and exit. Then you will be able to connect by SSH and execute some commands to recover the system.

**Comment by eldering** [comment]
In the master branch there is now a configuration setting "Diskspace error". When that limit of free space is hit, the judgedaemon will abort and report this. I think that should solve this problem, feel free to reopen if you think otherwise.

**Comment by iriszero** [comment]
I'm not sure that you may include this situation.

1. A judging takes place in and the output file eats the last byte.
2. Judgedaemon stops the judging and verdict it.
3. Judgedaemon would keep running and giving verdicts of  "COMPILE-ERORR" because there is not enough space for a binary to be compiled.
4. The administrator will be aware of it soon or later and try to connect the server and execute some commands to figure out but he/she can't do that. There may not exist any space for a single pipe on the disk.

**Comment by eldering** [comment]
I don't quite understand what you're trying to say with "I'm not sure that you may include this situation."
Are you questioning whether the case you describe would also be fixed by the "Diskspace error" configuration setting? Then the answer is yes: in the current master branch, a judgedaemon would gracefully exit (first finishing a current judging) and then throw an error when there is less free space available than configured. By default this is 1GB.

**Comment by iriszero** [comment]
Yes. You understood perfectly. I think I've not seen that part yet. Thank you.

**Comment by iriszero** [comment]
I'm digging up this again for some reason. I'm simply adding the reference for the community.
https://github.com/DOMjudge/domjudge/commit/de068b52b561bb46f66ff6fb3832b4c6aa65162b
