### ISSUE TITLE
Multiple custom output validators bug

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#285]
I think I've read somewhere that DomJudge doesn't fully support the output validator spec as stated on http://www.problemarchive.org/wiki/index.php/Problem_Format . 

We currently have the following setup;
```
problem/output_validators/0_grammar.cpp
problem/output_validators/1_output_validator.cpp
```

It seems that `0_grammar.cpp` is run, but `1_output_validator.cpp` is not.
This is confusing; either only support the `build`/`run` setup, and don't allow anything else, or fully support this setup with multiply output validator files.

We've fixed this by including `build` and `run` scripts that just run all available `*.cpp` files in order

**Comment by eldering** [comment]
Indeed, we do not (yet) fully support the Kattis problem format, see also #265 and #269.
This is partially since we "only" started building support for it 2 years ago, and it's not been a high priority. Also, it's not our plan to support the full specification there, but only a subset that would be included for use in the ICPC specifications listed on https://clics.ecs.baylor.edu/index.php/Main_Page

Anyways, indeed we only support a single output validator currently, so if you want to use more, then the simplest solution is to use `build`/`run` scripts to join them into a single validator.
