### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by AdrianELehmann** [DOMjudge/domjudge#287]
Add support for Docker, i.e. create an image to pull and run

**Comment by eldering** [comment]
There is already the live image, see https://github.com/DOMjudge/domjudge-packaging, and also the experimental https://github.com/meisterT/domjudge-docker (not sure how current that is).

Feel free to create a pull request to create a docker image, but please do so against the `domjudge-packaging` repository.

**Comment by AdrianELehmann** [comment]
Unfortunately https://github.com/meisterT/domjudge-docker is outdated an reliant on outdated packages

**Comment by nickygerritsen** [comment]
I am trying to get this up and running. It might take a bit but hopefully it will be cool.
Will do a PR to `domjudge-packaging` if it is done.

Probably there will be two sets of Docker images:
* One for running DOMjudge as maintainer. This will contain both the domserver and judgehost in one image and will use a Docker volume to mount the git repository inside the container. This is useful for people working on DOMjudge who do not want to setup a whole environment themselves or can not do this easily (because they use macOS or Windows)
* One for running a release version of DOMjudge. This will probably be a script that takes a DOMjudge version string, downloads the archive from domjudge.org and builds two Docker images from them. One for the domserver and one for the judgehost. We could (automatically) publish these images to Docker Hub, so people can just pull them and be up and running.

I will probably use some ideas from @meisterT's project.

Thoughts on this from any of the @DOMjudge/developers?

**Comment by meisterT** [comment]
Thanks Nicky for taking this. I pushed a WIP commit to my repo (which solves some but not all issues).

Sounds like a good plan to me.

**Comment by eldering** [comment]
Closing here, see the pull request in domjudge-packaging.
