### ISSUE TITLE
Disabling a contest causes an invalid endpoint call

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#295]
Every update to the contest is to be logged but disabling a contest means you cannot query the API for that contest anymore which in turn generates an error. Disabling works anyway.

**Comment by eldering** [comment]
Disabling a contest should probably be viewed as deleting it. But then we'd have to generate delete events for all elements inside it. And recreate them when re-enabling the contest... This makes me think that a dirty workaround is better.

**Comment by nickygerritsen** [comment]
If we only want to log the contest, can't we modify the `/contests/{cid}` endpoint to have an option to also return a contest if it not active / enabled and use that endpoint for the eventlog?
We then might also need to add the enabled-status to `Contest::serializeForAPI`.

**Comment by eldering** [comment]
That doesn't really solve our problem of how to present this in the API, which is not so much a technical, but more a design problem. The [Contest API](https://clics.ecs.baylor.edu/index.php/Contest_API#HTTP_methods) requires:
- Referential integrity: objects cannot refer to objects that don't exist. So if we delete a contest from the API, then we must also delete all problems, submissions, teams, under it.
- Notification of deletes in the event feed: so if we'd delete/recreate a contest, that would generate a large/huge amount of events.

Now, if we disable a contest, that does mean that we don't want to expose it anymore. But if we want to follow the API specification, then we'd have to go through lots of hoops to do so. I think the easiest is to special case a contest en/disable action (as far as changes inside the contest API endpoint) and simply remove the contest from view in the API, maybe with a 403 error code, but not generate an event for it.

**Comment by nickygerritsen** [comment]
But doesn't that break referential integrity? If we hide the contest from the API, but we still have problems, teams, etc. linked under it (which they are), aren't they then dangling from an API point of view?

**Comment by nickygerritsen** [comment]
As a side note: editing/deletimg any contest besides the currently active one should maybe not generate any event at all?
The Contest API does not say anything specific about this, but seeing as it assumes one active contest, this might make sense right?

Also, if you disable the current active contest but have another one that is active currently (i.e. we had two active before but the first one is the one the Contest API was interested in), that would probably also  mean we should send events for problems and teams switching?

All this seems quite difficult to fix correctly with "ugly hacks" maybe?

**Comment by eldering** [comment]
The current Contest API is indeed for a single contest, but with the intent of being extensible to a [Multi-contest API](https://clics.ecs.baylor.edu/index.php/Contest_API#Multiple_contest_API). Thus our behaviour of exposing as single contest the active one would have to change.
However, in that multi-contest API, I think that disabling a contest should completely remove access to it. Removing access would also remove access to the `event-feed` endpoint under it, so there's nothing there that has to be updated then. This is not strictly according to spec, because if we'd enable and re-expose the contest again, then in principle we should regenerate create events for all problems, teams, etc. but I think that's a reasonable alternative. Also, in practice we'd only disable a contest that is not actively followed, so it wouldn't cause any issues.

**Comment by meisterT** [comment]
This was fixed in the meantime.
