### ISSUE TITLE
Login into jury sometimes returns to wrong endpoint

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#297]
I land on
https://domjudge.bath.ac.uk/domjudge/jury/updates.php
and get
{"clarifications":[],"judgehosts":[],"rejudgings":[],"internal_error":[]}

**Comment by ubergeek42** [comment]
Gonna guess this has to do with symfony redirecting you to where you were
trying to go after you login. E.g. if you tried to go to
/domjudge/jury/contests.php, you'd get thrown to the login page, and after
successfully logging in, taken to /domjudge/jury/contests.php. I believe
prior to symfony you'd just get taken to jury/index.php

The reason you're getting that page is most likely because the jury page
does ajax requests for status updates, and then your session times out and
that was the last page it tried to access before throwing you back to the
login page.

This probably applies to the team page too since it does ajax requests as
well.

So I see two solutions: try to blacklist specific URLs we don't want to
redirect people to and send them to the index instead, or just always send
people to the index after logging in. Thoughts?

(I haven't looked at the code, so this is all conjecture at this point)

**Comment by eldering** [comment]
But if you're trying to revisit e.g. `/domjudge/jury/contests.php` then that should be visible in the referrer header, right? And then that page could be redirected to instead of the last requested page. Anyways, this also occurred to me a few times now, and I think it would be ideal to be redirected to the page you were trying to visit, but if not then the index is still better than the updates.php JSON "page".

**Comment by nickygerritsen** [comment]
I think Symfony *does* use the referer to determine where to redirect to; however of the last request before a session timeout is updates.php, that will be the referer and the system will redirect us to that location.

**Comment by nickygerritsen** [comment]
@ubergeek42 see my commit from just now. https://symfony.com/doc/current/security/form_login.html#using-the-referring-url suggests adding this and it seems to have fixed the issue.

Before, I could reproduce the problem by:

* Logging in and going to a jury page
* Removing the session cookie
* Wait for a call to updates.php
* Refresh

This now is no longer possible it seems.

**Comment by meisterT** [comment]
I see this again in the ICPC live branch and it also could explain login issues reported by Greg.

**Comment by meisterT** [comment]
See also e2e2926570035d34ebc712aba8ea0d7e1e53a56d for a temporary fix.

**Comment by thijskh** [comment]
Is this fix not just good enough? Have you seen any drawbacks from it in the last ¾ year?

**Comment by nickygerritsen** [comment]
I have. It is quite annoying to go to http://domjudge/jury/submissions/123 and then get a login prompt and get send back to http://domjudge/jury/

**Comment by thijskh** [comment]
Perhaps revisit this when we've moved everything to Symfony. Because the example mentions `updates.php`, which lives (lived) outside of the Symfony system, and therefore maybe confuses the logic there.

**Comment by nickygerritsen** [comment]
As now everything is in Symfony, I will re-enable this and we will find out if it still breaks.

I see in the Symfony code where it sets the provider target path:
```php
        // session isn't required when using HTTP basic authentication mechanism for example
        if ($request->hasSession() && $request->isMethodSafe(false) && !$request->isXmlHttpRequest()) {
            $this->saveTargetPath($request->getSession(), $this->providerKey, $request->getUri());
        }
```

So I think the AJAX updates will indeed be ignored now that everything is in Symfony.

**Comment by nickygerritsen** [comment]
One thing I found, which I'm not sure how (and if) to fix: if you go to `<domjudge>/team` without being logged in and log in as a user without a team or team privileges, you will be redirected to `<domjudge>/team` as expected, but then get a 403. Same holds for other URL's and roles of course.

But is this something we want to fix? If you go to `<domjudge>/team` while you *are* logged in as a non-team, you get the same result. Perhaps if we want to fix this, we might do the following:
* Somehow add an event to a 403 (I think this can be done) that sets a flash messsage that you are not allowed to access the page
* Redirect to `/`, which will redirect you to a page you *do* have access to. Or maybe the referrer? But that might be `/login`...

However, then we never throw 403's anymore, which also seems strange.

**Comment by thijskh** [comment]
No
