### ISSUE TITLE
To request options of configure script to enable/disable domserver/judgehost

### ISSUE THREAD

**Issue by easior** [DOMjudge/domjudge#305]
According to the documentation of domjudge, it is divided into three parts, that is, domserver, judgehost, docs. Although I still feel confusion regarding the relationship between domserver and judgehost(e.g. judgehost part is independent of domserver part or not?) , I request that configure script should afford some options to enable/disable domserver/judgehost during compiling phase. In fact, autotools will complain that libcgroup can't be found when domserver is only built. These options would be very useful to build domjudge by virtual of Gentoo ebuild while they are useless to Debian/Redhat Linux users.

P.S.
Could you tell me how to create an account for domjudge?

**Comment by eldering** [comment]
The `domserver` and `judgehost` are separate binary/installation targets of a single source: they share a good chunck of common code, but would typically be installed on separate machines. Since the dependencies largely overlap, we haven't looked into splitting this up yet. That would require some significant changes to the build process. Instead, as asked in #301 I propose to implement #304 instead, to keep the dependencies shared. See also the Debian packaging in https://github.com/DOMjudge/domjudge-packaging/tree/master/debian for examples how to build separate `domserver` and `judgehost` packages.

Finally, what kind of account are you looking for?

**Comment by easior** [comment]
@eldering Thank you for your comments. I hope some of implements you mentioned would be carried out soon. I have written an ebuild script for Gentoo in one of my GitHub repositories. It seemly works on my Gentoo box although it needs more testing. On the other hand, I also made a RPM Spec for Fedora to build RPM packages. The domserver part works well on my Fedora box. I don't know how to create many accounts for domserver  in the batches. Is there any bash/PHP/SQL script to reach this purpose? On the other hand, It's well-know that the systemd package is taken charge of the initial scripts on Fedora/CentOS instead of sysinit. Hence, I need some helps to adapt domjudge-judgedaemon to the control of systemd package.

**Comment by eldering** [comment]
For extended questions and discussions, please subscribe to the [domjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel) and ask there: we're happy to help (and could maybe even include your Gentoo/RPM packaging in https://github.com/DOMjudge/domjudge-packaging if it has reached mature quality), but this issue tracker is intended for bugs and features and not really meant or well-suited for discussions.
