### ISSUE TITLE
Disable .py autodetection to avoid confusing contestants

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge#351]
One thing I noticed in contests is that people, especially beginners, are confused by the existence of Python 2 and 3, and often mix them up. DOMjudge makes this a bit worse by auto-detecting `.py` files as Python 2, allowing contestants to upload a file and submit it without realizing it's the wrong language.

I suggest removing `.py` autodetection altogether, and only keeping `.py2` and `.py3`. This will force contestants to pick a Python version.

I know this is a "problem is between keyboard and chair" issue, but it happens commonly enough in contests I help with that I think it should be fixed at the IT level..

**Comment by meisterT** [comment]
This is trivially configurable in the web interface. If you've contestant who mix up these, either disable one or remove .py from the language extensions.

**Comment by SolalPirelli** [comment]
I know it's configurable, I'm just suggesting changing the defaults.

**Comment by eldering** [comment]
I agree with @meisterT: it is configurable, and having the `.py` extension by default allows people to submit their sources with the commandline submit client without having to explicitly specify a language, since `.py{2,3}` are not standard extensions.
I would be willing to be convinced to change the default for `.py` from version 2 to 3, if that would make more Python submissions work as expected.
