### ISSUE TITLE
Use isolcpus to isolate submissions from other running processes

### ISSUE THREAD

**Issue by TPolzer** [DOMjudge/domjudge#355]
Using the isolcpus should make timing of submissions more deterministic. It excludes all non pinned processes from running on a particular core (on which we can then pin the submission).

**Comment by eldering** [comment]
Ok, I was interested and did a little bit of reading. `isolcpus` is a kernel boot parameter only, you read what was set from either `/proc/cmdline` or `/sys/devices/system/cpu/{possible,isolated}`, the latter two are complementary lists.
I think we should test whether using this has an effect on runtime variance, and then we can simply document that you should pass something like `isolcpus=1-X` with `X` the number of CPU cores in the kernel command line on each judgehost, and run the judgedaemon with `-nY` option with Y in [1,X]. Of course X may depend on how many judgedaemons you actually want to run in parallel.

**Comment by eldering** [comment]
We tested this at the world finals: we ran a set of 156 jury submissions (3 more were excluded because they had variations due to TLE)  across 10 machines with identical hardware (6 CPU cores, 16GB ram), each running a single `judgedaemon -n0`. Half de machines had `isolcpus=0` as kernel parameter, the others not.
We did not see any significant change in testcase runtime average nor standard deviation across the two sets of machines:
```
with    isolcpus: COUNT(runtime) = 46995  AVG(runtime) = 0.349264 STDDEV_SAMP(runtime) = 0.9254717
without isolcpus: COUNT(runtime) = 46995  AVG(runtime) = 0.350097 STDDEV_SAMP(runtime) = 0.9258753
```

Our conclusion: this is not worth using, although it may be if you are running multiple judgedaemons per machine and/or with few CPU cores.

We'll add a simple remark about isolcpus in the documentation.
