### ISSUE TITLE
Port documentation changes to master

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#385]
Not all changes apply in the general case and we may want to keep the WF-specific changes behind some configuration.

**Comment by thijskh** [comment]
I believe this is done. Nearly all changes are generic enough in my view.
It remains the case that you need to copy-edit the team manual for your contest if you want it to apply very well and not contain irrelevant info. That can also be said of the WF. Not sure if we'd need extra config options.

You could ask yourself about the NL team manual since it's perpetually out-of-sync and costs time to keep up to date. Since there's no NKP anymore, should we keep that?

**Comment by meisterT** [comment]
Thanks for porting the fixes.

I'm in favor of deleting the dutch manual.
