### ISSUE TITLE
Low memory limit for Java fails

### ISSUE THREAD

**Issue by SolalPirelli** [DOMjudge/domjudge#423]
### Description of the problem / feature request

A problem with custom memory limit 65536 KB fails to be judged with Java: `Invalid initial heap size: -Xms-65536k`

Resetting the limit to the default of 524288 KB, which is much larger, works...

### Your environment

DOMjudge 5.3.2, Java 8 (openjdk-8-jdk)

### Steps to reproduce

- Set problem memory limit to 65536 KB (in my case, done when importing a problem archive)

### Expected behaviour

Requesting less memory than a known-good config should not cause problems.

**Comment by eldering** [comment]
The cause is that by design the JVM is included in the memory limit. Since the JVM takes about 64MB, and in Java you have to separately reserve memory for the stack (also 64MB by default), this then leaves -64MB for the heap. See the calculation of `MEM*` variables in https://github.com/DOMjudge/domjudge/blob/master/sql/files/defaultdata/java_javac_detect/run for the details.
You can adapt that script yourself, but we're not really eager to make language specific exceptions in the core code to accomodate specific languages.

**Comment by SolalPirelli** [comment]
OK, thanks.

**Comment by eldering** [comment]
I will add an error message in the compile script that at least makes clear why this happens.
