### ISSUE TITLE
Truncate team name on scoreboard

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#431]
Currently a long team name get displayed in full length on the scoreboard. This creates a suboptimal layout wasting a lot of space on the team column and potentially pushing the problem columns out of the window. We should probably restrict the team column to a maximum width, and truncate the team name (don't wrap to a new line, since it would create rows with uneven height).
Attached a screenshot from UKIEP. Note also that the category leader button adds to the problem.
![screen](https://user-images.githubusercontent.com/4692022/47256210-53194b80-d47c-11e8-94b6-3392036faff7.png)

**Comment by meisterT** [comment]
Note: We had that width restriction before and removed it during the scoreboard redesign last year since we changed the width all the time. So we have to make sure we do it better than what we've already had ;-)

**Comment by tuupke** [comment]
What about a config value, to set a max-width (0 for no max-width) and then add a gradient to white on the rhs, to show that the teamname is larger than would fit in the field.

We could also add ellipses, but since they look similar to three periods this might conflict with teamnames.
![image](https://user-images.githubusercontent.com/2218324/55669920-f9afa800-5874-11e9-8bc7-c0a69c04fc3b.png)

**Comment by nickygerritsen** [comment]
I’m in favor of the former!
