### ISSUE TITLE
Import teams tsv is broken

### ISSUE THREAD

**Issue by ubergeek42** [DOMjudge/domjudge#438]
### Description of the problem / feature request
import `teams.tsv` is broken

### Your environment
domjudge master, running in docker contributor container

### Steps to reproduce
Import a teams.tsv with more than 1 team

### Expected behaviour
The teams are imported

### Actual behaviour
Only the last team is imported

### Any other information that you want to share?
It seems like `externalid` being declared `unique` breaks `replace into`, as mysql sees an empty external id as identical to the last row it inserted, so it replaces it. Thus you only get the last team imported.

Also, its horribly slow(Tested with a teams tsv with ~120 teams)

**Comment by nickygerritsen** [comment]
This was because of multiple reasons:

* If the external ID of a team is `null` or `''`, we export that as an empty string. However, importing that again broke the import. I have added a check whether it is empty and then set it to `null`.
* We didn't export external ID's of affiliations (and they had the same problem as above). Fixed that as well
* Unrelated, but also fixed: at least for the NWERC, the ICPC CMS currently has a `'null'` string value for the Team Number column. I changed the code such that it uses the external ID as teamid in this case.
* Lastly, for the speed I now do all the eventlog calls at the end, to not have 120 of them.
