### ISSUE TITLE
clarification categories vs queues while importing system.yaml 

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#453]
We currently import the system.yaml (https://clics.ecs.baylor.edu/index.php?title=Contest_Control_System_Requirements#system.yaml) as part of the contest.yaml. While doing so, we set a bunch of config variables.

One variable that we read is `clar-categories`. We import this as clarification category (see
https://github.com/DOMjudge/domjudge/blob/master/www/jury/impexp_contestyaml.php#L143). I would argue that now that we have them clarification queues is the better destination since these should not be exposed to contestants.

**Comment by thijskh** [comment]
So we import the “clar-categories” to queues.
And we create per-problem “categories”.
Do we then still need the ability to configure additional categories?

**Comment by meisterT** [comment]
I agree with Thijs and we should remove the old categories in favor of the new queues to simplify code and handling in the web interface.

**Comment by thijskh** [comment]
Working on the clarification interface, my conclusion is that the current setup is really complex due to various "categorizing" methods being bolted on. A clarification can have an associated problem, a category, and a queue; which are half-combined into the interface. All the while I wonder if it should not rather be associated to a contestproblem instead of a problem. Really needs some disentangling work...

**Comment by thijskh** [comment]
Now everything (for jury) is migrated to Symfony and Twig, it has become easier to tackle these problems one by one.

**Comment by meisterT** [comment]
Thijs, can you please update this with the current state?

**Comment by thijskh** [comment]
Nothing has been changed on the import of system.yaml specifically. But the bigger question is how we want "categories", "problems" and "queues" to work.

Better to discuss this in person I think. The original issue (system.yaml import) does not seem urgent specifically.

**Comment by eldering** [comment]
Since https://github.com/icpc/ccs-specs/commit/383c93dcd37720f481526d822d9445f41c3510c5 the CCS specification does not require importing `system.yaml` anymore and the data it contained has been hardcoded in the specification in the sense that the CCS should support predefined "clarification categories" `General`, `SysOps` and `Operations`, that I think we should indeed translate to queues (as we do already).

So the `system.yaml` import code can be removed.
