### ISSUE TITLE
Be able to save/download graphs

### ISSUE THREAD

**Issue by thijskh** [DOMjudge/domjudge#535]
It has been requested that you be able to save/download the graphs in the analytics, submissions etc pages. This so you can do something nice with them, e.g. include in a presentation.

**Comment by meisterT** [comment]
Preferably, downloading these graphs even works from the API.

**Comment by nickygerritsen** [comment]
I’m not sure how trivial that is, as generating currently happens completely in JavaScript. Either we need nodejs or we need to move this to php?

**Comment by thijskh** [comment]
Indeed that would mean completely reinventing the graph generation. Let's keep this issue confined to being able to download the graphs as they are now, from the UI.

**Comment by DerBaer0** [comment]
The old statistics page with the d3 plots included a JavaScript function that offered to download the graph by just Base64-Encoding the html/svg code. Simple, but maybe not the cleanest solution though.
For the new nvd3 plot, this does not work out of the box because some stylesheets need to be added as well somehow.

**Comment by nickygerritsen** [comment]
I found a way to copy in the CSS, so we can now download graphs again 🎉
