### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jahirfiquitiva** [DOMjudge/domjudge#580]
### Description of the problem / feature request

Hello, this isn't a real issue but a question. Basically, I'm trying to understand the `Boolean switch search` problem.

In the pdf, the input and output differ from the ones in the default test case 🤔 

Thanks

**Input in PDF:**
```
1
5
1 1 0 1 0
false
true
```

**Input in Test Case:**
```
1
5
1
1
0
1
0
```

**Output in PDF:**
```
READ 2
READ 1
OUTPUT 1
```

**Output in Test Case:**
```
OUTPUT 1
```

### Your environment
> Include details about your installation here. 
> - DOMjudge version: 7.0.0
> - Operating system / Linux distribution and version: Debian 9
> - Webserver: Apache

**Comment by nickygerritsen** [comment]
So "Boolean switch search" is a so-called interactive problem, as stated in the PDF. The PDF also states:

> The input (and output) after that is a sample interactive session.

Thus the
```
false
true
```
and the
```
READ 2
READ 1
```

from the PDF are an example of interaction between the problem and the team submission:
* The team asks the program to `READ 2`, i.e. i.e. 'give me the output at index 2 of the array`, which the program responds to with a `false`, since the value at index 2 (the third value, since it is zero-indexed) is `false.
* Then the team asks the program to `READ 1`, where the program responds with `true`, since that is the value at the first index.
* Now, since the team knows the value at index `1` is `true` and the one after that is `false`, it knows at position `1` a `true` is followed by a `false` and hence it outputs `OUTPUT 1`, a correct answer to the problem.

Note that `OUTPUT 3` would *also* be a correct answer; this problem can have more than one answer (but it always has at least one since the first value of the array is guaranteed to be `true` and the last one is guaranteed to be `false`).

I hope this makes it clear what this problem does?

**Comment by jahirfiquitiva** [comment]
Thanks for the explanation @nickygerritsen .. Anyways, for me I still don't understand where 

```
READ 2
READ 1
```

is received ... is it like an extra set of input provided by the program executor?

**Comment by nickygerritsen** [comment]
This program: https://github.com/DOMjudge/domjudge/blob/master/sql/files/examples/boolfind_run/runjury_boolfind.c
Is run in between the jury input and the team submission and it will receive these READ commands.
