### ISSUE TITLE
boolfind-test-loop.cc Hangs the judgehost?

### ISSUE THREAD

**Issue by lsmll** [DOMjudge/domjudge#605]
I recently installed DomJudge 7.0.2 and ran the test mentioned in section 4.5 of the admin manual. Everything is fine except for one submission, boolfind-test-loop.cc. Apparently, this submission doesn't get terminated due to timeout (I waited 2min and the time limit is 5 sec), and it hangs the judgehost indefinitely. I don't know if there is something wrong with my installation or it is a bug either in the interactor executable or in the judgehost.
By the way, the Judging verifier doesn't seem to work, it says none of the submissions has magic string. Although that's a minor issue compared to the issue above.

**Comment by eldering** [comment]
Sorry for the slow reply. Indeed, I can reproduce this on a clean install from `master` branch.

**Comment by eldering** [comment]
Ok, I investigated this, and it's not _quite_ a bug. The problem is that writing interactive program validators is *tricky*.
So `boolfind-test-loop.cc` writes `READ 0` in an infinite loop. This goes into a pipe that `runpipe` creates and gets sent to the jury validator. In this case https://github.com/DOMjudge/domjudge/blob/master/sql/files/examples/boolfind_run/runjury_boolfind.c#L48, which simulates slow responses (which may happen if the jury validator needs to do something computationally heavy). Since https://github.com/DOMjudge/domjudge/commit/8d0c4c04fa0109e375d067f93d0598a6d254e61a the pipe buffer size is set to the maximum, which is 1MB. Now in the 6 seconds before `boolfind-test-loop.cc` hits the timelimit, it can probably easily fill up that pipe buffer, and then the jury validator still slowly processes those lines. Given that each line contains 7 bytes, that's about 1024*1024/7 msec ~ 150 seconds. So it should finish...
Note that these are issues that one has to be careful about when writing interactive validators and there's not really a solution from the system side. As a fix I will reduce the artificial delay to 0.1 msec, so that the validator only tabkes about 15 seconds to finish.

**Comment by eldering** [comment]
On the validator string: do you submit these test submissions as a jury/admin user? If I'm not mistaken magic string detection is only done in this case.

**Comment by lsmll** [comment]
Thanks for the reply. I guess I'll just not use any interactive problems in a contest for now. As for the magic string problem, indeed I didn't submit as a jury user, so that's not a bug.
