### ISSUE TITLE
Set rejudgings as lower priority for pickup by a judgehost

### ISSUE THREAD

**Issue by eldering** [DOMjudge/domjudge#639]
Currently, when you start a rejudging with a big set of submissions, this will DoS the judging queue, since those submissions have the same priority as any normal, new submissions.

In most cases, you'd probably like to make them lower priority.

**Comment by baierjan** [comment]
Except in cases, where all submits are wrong and you really need to rejudge as fast as possible and you need to assign it on one judgehost with higher priority.

**Comment by thijskh** [comment]
So need an option on a rejudging: priority =low,high?

**Comment by eldering** [comment]
I'm not sure we need an extra option. First, it's feature creep that I'd prefer to avoid unless really necessary.
Secondly, if the low priority rejudgings don't get picked up in the gaps when the judging queue is empty, then you're already running at/over judgehost capacity, and prioritizing those rejudgings will create bigger delays for the normal submissions, which I think is also very undesirable.
Finally, with this feature you can still use the old way of rejudging (without creating a "rejudging"), which will give the submissions to be rejudged the same priority. The fact that you can't review before applying seems not too unreasonable in such an emergency situation. We should then explain the differences a bit more clearly.

**Comment by meisterT** [comment]
I was thinking about this for a while. I think I disagree with the assumption in the first comment and would argue that you would want to fix a possible mistake in the test cases as soon as possible. This is to make sure that teams who received an incorrect verdict instead of an "accepted" receive their balloon as soon as possible (and don't waste even more time on this problem).

The old way of doing rejudges doesn't have the overview/review functionality so it's not a good replacement. I would even say we should remove that for all non single submissions rejudgings but that's a separate discussion.

**Comment by meisterT** [comment]
Now with the new judgehost API this should be trivial to implement. Let the person who starts the rejudging decide the priority and use it in the judgetasks
