### ISSUE TITLE
Scoreboard API mixes different sortorders

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#648]
Currently, our `/api/contests/<x>/scoreboard` API endpoint returns the scoreboard for all (visible) sortorders.
This means that you first get all (ordered) scores for sortorder `0`, then those for sortorder `1`, etc.

However, the API spec doesn't have this notion of sort order, thus if you compare a scoreboard with > 1 visible sortorder to a CDS scoreboard, you will get a lot of differences.

See for example https://eapc2019.131.155.69.89.nip.io/api/contests/3/scoreboard. Note that team `40` has rank `1` again, since that is where a new sortorder starts.

Is this something we should do something about? Can we even?

**Comment by eldering** [comment]
I guess the "solution" would be to remove sortorder. OTOH, you don't have to use it, and you can always make sure that only one sortorder is visible. I would want to do anything that makes the list of teams on the scoreboard out of sync with what's in the teams endpoint.
What we could do it to add a `sortorder` attribute to the scoreboard in case there is more  than one, so that a client would at least be able to spot the attribute and notice that it's an unknown feature or correctly handle it.

**Comment by nickygerritsen** [comment]
Proposal: add an optional (get) argument to specify the sortorder to the API. If none is given, give the "lowest" sortorder (i.e. 0).
