### ISSUE TITLE
Come up with a decent way to set up permissions on var/cache/{prod,dev}

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#650]
When you run the database migrations as a user that differs from the webserver / FPM user, the `var/cache/prod` (or `dev`) directory will be owned by that user, since we use a Symfony shell command to migrate and load initial data.
If you then want to do anything in DOMjudge, it will crash.

We have multiple people run into this already, so we should probably fix it. Or at least add a clear note to the documentation that you need to change the permissions of that directory.
When running the migrations as root, we can just add a `chown` at the end, but if you run it as a different user, that is not possible...

**Comment by thijskh** [comment]
What do you think of this approach?

```diff
--- a/sql/dj_setup_database.in
+++ b/sql/dj_setup_database.in
@@ -8,6 +8,7 @@ set -e
 
 ETCDIR="@domserver_etcdir@"
 WEBAPPDIR="@domserver_webappdir@"
+WEBUSER="@WEBSERVER_GROUP@"
 
 PASSWDFILE="$ETCDIR/dbpasswords.secret"
 
@@ -124,9 +125,9 @@ symfony_console()
        fi
 
        if [ -n "$DATABASE_URL" ]; then
-               DATABASE_URL=$DATABASE_URL ${WEBAPPDIR}/bin/console -v $ARG "$@"
+               DATABASE_URL=$DATABASE_URL sudo -u ${WEBUSER} ${WEBAPPDIR}/bin/console -v $ARG "$@"
        else
-               ${WEBAPPDIR}/bin/console -v $ARG "$@"
+               sudo -u $WEBUSER ${WEBAPPDIR}/bin/console -v $ARG "$@"
        fi
 }
```

**Comment by thijskh** [comment]
The Symfony recommended way is to warm up the cache so no more writes are needed at runtime. (Which seems like something we should be doing anyway.)

This works but only not with Doctrine :-( One approach would be to switch doctrines cache to APC instead of files. To me that seems an improvement anyway. What do you think?

A good alternative to me is what you say:
>  When running the migrations as root, we can just add a chown at the end, but if you run it as a different user, that is not possible...
As for the second part of that sentence: why just not disallow that then. If we want to make it less fragile, we should adhere to the "there's only one way to do it" principle. One way that is robust. And check at the start of the script if it's run correctly.

**Comment by nickygerritsen** [comment]
I agree that less options is better, since people are always struggling. Using APC for Doctrine makes sense but it does require APC, although that is built in nowadays right?

**Comment by thijskh** [comment]
Cache warmup is implied by cache:clear. However, we do not do a cache:clear on domserver-install (only on maintainer-install). Seems like we should be doing that? If I (re)install the domserver I think I do not want a stale cache.
