### ISSUE TITLE
Uncaught PHP Exception

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge#934]
Currently in the gitlabci pipeline we get these exceptions:

```[2020-11-23 21:16:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Found more than one @EXPECTED_RESULTS@ in file." at /opt/domjudge/domserver/webapp/src/Controller/API/SubmissionController.php line 235 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Found more than one @EXPECTED_RESULTS@ in file. at /opt/domjudge/domserver/webapp/src/Controller/API/SubmissionController.php:235)"} []```

As I think its valid to have multiple RESULTS this might need to be handled differently (as valid input should not lead to exceptions).

Main reason why this should be fixed is it has a high level of "red herring" which makes debugging harder than it should be.

**Comment by thijskh** [comment]
Where can I find an occurrence of this?

**Comment by mvr320** [comment]
It happens in every integration job I think:
https://gitlab.com/DOMjudge/domjudge/-/jobs/875740150/artifacts/file/gitlabartifacts/symfony.log

**Comment by meisterT** [comment]
This happens because of https://github.com/DOMjudge/domjudge/blob/master/tests/bad-expected-result-multiple-in-file.c - which was explicitly added to test this behavior in https://github.com/DOMjudge/domjudge/pull/846 by @RagnarGrootKoerkamp 

I am not sure what the optimal behavior is. You could also argue that if one file contains multiple expected results, you merge the mentioned verdicts. In the judging verifier these with multiple outcomes are listed separately anyway.

cc @eldering who probably has an opinion on this.

**Comment by mvr320** [comment]
@meisterT The spec probably does not allow this because I think Ragnar knows the spec.

My main issue is that the exception is thrown in a hard to debug test, so if it can be moved to the unit testing (where also the API spec tests are partly done) it would still be tested but would not be a _red herring_ when someone makes a PR and then tries to find out why the PR fails.

**Comment by RagnarGrootKoerkamp** [comment]
This is not in the spec currently, but the way I wrote the current pr https://github.com/Kattis/problem-package-format/pull/4/files for it does require exactly one mention of it.

IIRC this is also because the DOMjudge code only finds the first mention anyway, so I just added a test to avoid confusion.

**Comment by eldering** [comment]
What's the status of this?

**Comment by eldering** [comment]
As also mentioned in slack: I think that having multiple expected results spread across different files should be considered an error: this is easily a mistake, and I see no reason why you'd do this on purpose. So I'd propose to reject this submission with an error.

**Comment by vmcj** [comment]
> As also mentioned in slack: I think that having multiple expected results spread across different files should be considered an error: this is easily a mistake, and I see no reason why you'd do this on purpose. So I'd propose to reject this submission with an error.

Over multiple files I might agree, I can see an usecase where it is intended but most of the time that would be wrong.

But I meant the case of:

```
EXP_RES: A
EXP_RES: B
code
```
which would be equal to:
```
EXP_RES: A, B
code
```

**Comment by eldering** [comment]
What is the reason to support that too? I prefer to stick to a single syntax.

I was also thinking that it might be better to do accept any submission (since it's just meta-data), but simply not recognize any expected result when parsing fails, so it's easier to detect that we didn't parse any `@EXPECTED_RESULTS@` strings.

**Comment by vmcj** [comment]
Given that this is not a bug, and there is a PR to remove this herring from the log, I'll close this issue.
