### ISSUE TITLE
Error: Maximum execution time of 30 seconds exceeded for generate password

### ISSUE THREAD

**Issue by zargarzadehm** [DOMjudge/domjudge#936]
### Description of the problem
 We had 90 teams in a contest and every team had a user, to generate a password for these teams I got this error:
```
Error: Maximum execution time of 30 seconds exceeded
```

### Your environment
 - DOMjudge server version 7.3.1
 - docker
 - Webserver nginx

### Steps to reproduce
  - create a relatively large number of teams with users for those teams
  - generate a password for them

### Expected behaviour
  *  Create passwords for all teams

### Actual behaviour
  *  500 Internal Server Error

### Any other information that you want to share?
![2020-12-07 00 07 36](https://user-images.githubusercontent.com/35424774/101398635-a3192d80-38e3-11eb-9809-9460eb35f9db.jpg)

  * i resolved this issue with add line `set_time_limit(300);` to function [generatePasswordsAction](https://github.com/DOMjudge/domjudge/blob/75b2dded8f3b12bf0bddbfa3d2778e436867b69a/webapp/src/Controller/Jury/UserController.php#L320) in  `webapp/src/Controller/Jury/UserController.php`

  * Another solution is set to limit teams that can generate password or option for select teams

  * another solution that @thijskh suggested in the slack channel was to lower the hash cost.

**Comment by nickygerritsen** [comment]
I wonder what the clean solution(s) would be:
* We set `set_time_limit(-1)` on this page and add a warning on the page: `Please be aware that this will take some time`.
* We move the code to a command.
* We do both, by moving the code to a service that both can use.

**Comment by mvr320** [comment]
Why is it a bad idea to do this in batches? So reset only **n** accounts per pass? As I think you probably also want to paperprint these batches and its very hard to find out if something takes "some" time or is just stuck.

**Comment by nickygerritsen** [comment]
We could do something similar to the scoreboard cache refresh page, which outputs something after each processed item.
Doing it in batches would mean someone needs to press the button a couple of times, that doesn't sound very user friendly.

**Comment by thijskh** [comment]
Maybe we should explore lowering the hash cost. Generating 90 passwords does not seem like an extreme usecase.

**Comment by nickygerritsen** [comment]
I agree that 90 is not that much. Looking at some ICPC contests we have around ~128 teams and thus users.
We currently have a cost of 10. Lowering it basically means a higher attack chance right? It seems that lowering the cost by `1` halves the time to generate a password, but also the time to verify one and thus to bruteforce.

**Comment by thijskh** [comment]
We currently set the algorithm to "auto" it seems which means Argon2 and that does not use the cost parameter. Adding time_cost (the Argon2 parameter) with 3 not solve the problem.

Setting it to "auto" when that does not mean it will automatically work when changed is not useful so I propose to fix it on bcrypt.

Setting the hash cost quite low, with "8" it works fine for me for 300 users. But there's really no justification for any high cost in the context for DOMjudge I believe. The passwords we generate are also intentionally really short (because of the contest floor assumption).

For predictability I would set the algo to bcrypt. For our current passwords that we auto generate a low cost is not a problem. This password length can be discussed but is that on topic here?

Two possible solutions:
- Put a low cost in our default config anyway (5 or 7)?
- Set a lower cost when we are auto generating passwords in bulk. Because our generated passwords are not strong. A user-chosen password (self-registration) might be.

**Comment by eldering** [comment]
A few notes:

- I think the fact that autogenerated passwords are short would warrant a higher hash cost to compensate if anything.
- All of this is to protect the passwords in case these hashes are leaked. That most likely means someone got read access to the DOMjudge DB. But in the default setup that also implies write access, so you could just overwrite the password, or add an extra account to the same team. So I don't think these hashes are _that_ important.

I think my preferred solution would be to pick a hashing method/cost with a predictable time expense globally (and configurable) and/or make sure the bulk generate password call doesn't time out in PHP code.

**Comment by nickygerritsen** [comment]
> I think my preferred solution would be to pick a hashing method/cost with a predictable time expense globally (and configurable) 
It is already configurable by editing the `webapp/config/packages/security.yaml` file of course.

> and/or make sure the bulk generate password call doesn't time out in PHP code.

I think I agree. The easiest to do the latter is set a higher timeout. But I think indeed the suggestion that Thijs made to lower the cost for autogenerated passwords only makes sense? I'm not sure if that is easy to do though.

**Comment by thijskh** [comment]
> I think the fact that autogenerated passwords are short would warrant a higher hash cost to compensate if anything.

They are short but this is secure in the conext of a contest floor where you do not have days time to guess someonelse's passwords. A high hash cost does not add value in that scenario. If we envision other scenarios (e.g. where someone has a few weeks time), just upping the hash cost is not enough and we should make 12+ char passwords.

Upping the max execution time alleviates the problem for smaller contests (300 teams) but then still keeps the problem for 1000+ team contests or at least they have a really poor UI where the request 'hangs' for many minutes without feedback.

I think in the context of DOMjudge low hash costs are likely to be very acceptable and they are the simplest solution with the least wasted cycles.

**Comment by thijskh** [comment]
Maybe an interesting question is why it worked in 7.2 and fails in 7.3? Or is it a coincidence that it has not been reported earlier?

**Comment by nickygerritsen** [comment]
Argon2 is only available since php 7.2, so maybe it’s more related to that?

**Comment by thijskh** [comment]
I'm talking about DOMjudge versions 😀

**Comment by eldering** [comment]
I'm not opposed to reducing the hashing cost, but I think it's best to have a single consistent cost. Otherwise it becomes really unclear when a password has a more or less secure hash. Also, such special cases might easily get overlooked in code and years later we might find out that that hash cost by now is too low to be considered reasonably safe.

So what about switching back to bcrypt by default (possibly with a lower than default cost) and also increase the PHP script timeout if necessary to support 300+ passwords?

**Comment by nickygerritsen** [comment]
> I'm talking about DOMjudge versions 😀

I was aware. What I meant is that pho 72 and later are more common now than they were in the beginning of 2020 (because of both Debian and Ubuntu releasing versions with it)

**Comment by meisterT** [comment]
Just one additional data point: I also ran into the same issue while importing 140 team accounts via the API.

**Comment by thijskh** [comment]
Having a higher hash cost also significantly impacts API and thus judging performance. Maybe we should advise against setting a higher hash cost in any case.

**Comment by thijskh** [comment]
What about this approach:
- When generating a password for users we always generate one of length 16 We keep the character set we currently have that is all lowercase without 1 and i etc.
- When generating a password for a machine (e.g. judgehost) we use length 32 with more characters (the 'extra entropy' setting in `Utils::generatePassword()`
- We impose a minimum length in the UI of 10 chars for setting a password
- We set a hash cost of 7 in parameters but do not advise to change it.

@mvr320

**Comment by mvr320** [comment]
> What about this approach:
> 
>     * When generating a password for users we always generate one of length 16. We keep the character set we currently have that is all lowercase without 1 and i etc.
I think thats fine, although a bit hard to type (12 would also be in fine I think..)

> 
>     * When generating a password for a machine (e.g. judgehost) we use length 32 with more characters (also uppercase and some special chars; the 'extra entropy' setting in `Utils::generatePassword()`
Yes,
> 
>     * We impose a minimum length in the UI of 10 chars for setting a password
> 
>     * We set a hash cost of 7 in parameters but do not advise to change it (in docs nor in configchecker).
I had that check because of @eldering his comment on a parameter which can be forgotten. If you think thats not needed I'm fine with removing it. 
> 
> 
> @mvr320

But in general, I think that setting the machine password to 32 with cost 7 would be all which is needed, and the rest would be fine as we already had as those machine accounts are the only accounts which try to login so often but don't keep the session.

**Comment by vmcj** [comment]
Various PRs have decreased the hash costs. The side effect of the slower login time for the judgedaemon is also removed.

We can re-open this when we find new issues.
